### ISSUE TITLE
Useing JsonDeser.of() and custom schema  to resolve JSON format message error

### ISSUE THREAD

**Issue by gwnszbd** [streamnative/pulsar-flink#102]
my code :
1.use JsonDeser.of()
val desc: JsonDeser[MyBean] = JsonDeser.of(classOf[MyBean])
val source: FlinkPulsarSource[MyBean] = new FlinkPulsarSource(serverUrl,adminUrl,desc,props)

2.use custom schema
val source: FlinkPulsarSource[MyBean] = new FlinkPulsarSource(serverUrl,adminUrl,new JsonSchema(),props)

val dataStream = env.addSource(source)
dataStream.print()
env.execute("pulsar_flink")

ERROR log
2020-06-24 17:48:28 ERROR ReaderThread [org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.run(ReaderThread.java:115)]: Error while closing Pulsar reader org.apache.pulsar.client.api.PulsarClientException: java.lang.InterruptedException
2020-06-24 17:48:28 ERROR FlinkPulsarSource [org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:610)]: Failed to cancel the Pulsar Fetcher java.lang.RuntimeException:Failed to remove cursor for persistent://dev/dbtest/flink-partition-0
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:272)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.cancel(PulsarFetcher.java:419)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:608)
	at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:134)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:157)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:508)
	at org.apache.flink.runtime.taskmanager.Task.cancelInvokable(Task.java:1281)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:773)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Client instance has been closed.
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyClient.checkNotClosed(JerseyClient.java:327)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.checkNotClosed(JerseyWebTarget.java:140)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:151)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.topicPath(TopicsImpl.java:962)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscriptionAsync(TopicsImpl.java:640)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscription(TopicsImpl.java:625)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:265)
	... 9 more

2020-06-24 17:48:28 ERROR Task [org.apache.flink.runtime.taskmanager.Task.cancelInvokable(Task.java:1284)]: Error while canceling task Source: Custom Source -> Sink: Print to Std. Out (1/1).
java.lang.RuntimeException: java.lang.RuntimeException: Failed to remove cursor for persistent://dev/dbtest/flink-partition-0
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:611)
	at org.apache.flink.streaming.api.operators.StreamSource.cancel(StreamSource.java:134)
	at org.apache.flink.streaming.runtime.tasks.SourceStreamTask.cancelTask(SourceStreamTask.java:157)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.cancel(StreamTask.java:508)
	at org.apache.flink.runtime.taskmanager.Task.cancelInvokable(Task.java:1281)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:773)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Failed to remove cursor for persistent://dev/dbtest/flink-partition-0
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:272)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.cancel(PulsarFetcher.java:419)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:608)
	... 7 more
Caused by: java.lang.IllegalStateException: Client instance has been closed.
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyClient.checkNotClosed(JerseyClient.java:327)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.checkNotClosed(JerseyWebTarget.java:140)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:151)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.topicPath(TopicsImpl.java:962)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscriptionAsync(TopicsImpl.java:640)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscription(TopicsImpl.java:625)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:265)
	... 9 more

PS: I try to print type of datastream ,it is GenericType<com.kt.bd.pulsar2flink.Driver.MyBean>
when is use new SimpleStringSchema() ,it is String and use new SimleSringSchema() it is correct
I'm not sure this information is useful.

**Comment by gwnszbd** [comment]
jar vsersion info:
<fastjson.version>1.2.66</fastjson.version>
<flink.version>1.10.1</flink.version>
<pulsar.flink.connector.version>2.4.20</pulsar.flink.connector.version>

**Comment by gwnszbd** [comment]
Definition of my bean：
case class MyBean(abnormalPass:Int,allMoney:Int,authorizeLotCount:Int,eventTime:Long)

and when I change to a javabean class ,It is work.
well,Why does this schema(JsonDeser.of()) not support case class?

**Comment by jianyun8023** [comment]
`removeCursor` is a known bug because the client was closed by mistake. It has been fixed in version 2.5.0. I did not find any JSON related errors in your log. You can upgrade to the new version to see if it can be resolved.
