### ISSUE TITLE
[BUG] Flink Pipeline going to failing state with Error : start message id beyond the last commit

### ISSUE THREAD

**Issue by ritik-raj23** [streamnative/pulsar-flink#106]
**Describe the bug**
Seeing Below Error .When followed following steps.
1.      Placed pipeline and flink job was running.
2.      Started streaming data to source topic and is in progressing during below steps.
3.      Process triggered to upgrade to the latest connector .
4.      The failOnDataLoss was set to false before the connector upgrade.

2020-07-10 14:48:46.334 [...] INFO org.apache.flink.runtime.taskmanager.Task - Source: opr_event -> (...) (4/8) (38127628da3ccada63fb0ad1e0987ada) switched from RUNNING to FAILED.
java.lang.RuntimeException: start message id beyond the last commit
    at org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.skipFirstMessageIfNeeded(ReaderThread.java:156) ~[pulsar-flink-connector_2.11-2.4.23.jar:2.4.23]
    at org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.run(ReaderThread.java:98) ~[pulsar-flink-connector_2.11-2.4.23.jar:2.4.23]
 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by sijie** [comment]
@codelipenghui Can you help fix this issue - https://github.com/streamnative/pulsar-flink/blob/671e7b51889c82568629463657cb9dddac2a5fa1/src/main/java/org/apache/flink/streaming/connectors/pulsar/internal/ReaderThread.java#L159 ?

**Comment by codelipenghui** [comment]
close via #107

**Comment by codelipenghui** [comment]
@ritik-raj23 This issue was fixed by #107 and we have released at https://bintray.com/streamnative/maven/io.streamnative.pulsar-flink/2.4.27  https://bintray.com/streamnative/maven/io.streamnative.pulsar-flink/2.4.28

Please check.
