### ISSUE TITLE
[BUG]Restart the program to verify whether to continue consumption from the last consumption location

### ISSUE THREAD

**Issue by gwnszbd** [streamnative/pulsar-flink#108]
val source: FlinkPulsarSource[Array[ComeDetailBean]] = new FlinkPulsarSource(serverUrl,adminUrl,desc,props)
source.setStartFromSubscription("gpp_come")
=========================================================
I set the substraction name to verify whether the program will consume from the last location after it restarts

but I get error log:

2020-07-15 15:45:52,745 INFO  org.apache.pulsar.client.impl.ConsumerImpl                    - [persistent://cd/dev/flink_gpp_come_1-partition-1][gpp_come-reader-5b05e44e2c] Subscribing to topic on cnx [id: 0xf19c64e0, L:/10.52.10.21:59634 - R:112.124.209.229/112.124.209.229:16656]
2020-07-15 15:45:52,746 INFO  org.apache.pulsar.client.impl.ConsumerImpl                    - [persistent://cd/dev/flink_gpp_come_1-partition-2][gpp_come-reader-d9f531ffe6] Subscribing to topic on cnx [id: 0x15ab56f5, L:/10.52.10.21:59638 - R:112.124.209.229/112.124.209.229:16656]
2020-07-15 15:45:52,749 INFO  org.apache.pulsar.client.impl.ConsumerImpl                    - [persistent://cd/dev/flink_gpp_come_1-partition-0][gpp_come-reader-db3e0364c5] Subscribing to topic on cnx [id: 0xdb18977d, L:/10.52.10.21:59636 - R:112.124.209.229/112.124.209.229:16656]
2020-07-15 15:45:52,750 INFO  org.apache.pulsar.client.impl.ConsumerImpl                    - [persistent://cd/dev/flink_gpp_come_1-partition-2][gpp_come-reader-d9f531ffe6] Subscribed to topic on 112.124.209.229/112.124.209.229:16656 -- consumer: 13
2020-07-15 15:45:52,758 INFO  org.apache.pulsar.client.impl.ConsumerImpl                    - [persistent://cd/dev/flink_gpp_come_1-partition-2][gpp_come-reader-d9f531ffe6] Get topic last message Id
2020-07-15 15:45:52,761 INFO  org.apache.pulsar.client.impl.ConsumerImpl                    - [persistent://cd/dev/flink_gpp_come_1-partition-2][gpp_come-reader-d9f531ffe6] Successfully getLastMessageId 698660:0
2020-07-15 15:45:52,762 ERROR org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread  - the start message id is beyond the last commit message id, with topic:persistent://cd/dev/flink_gpp_come_1-partition-2
2020-07-15 15:45:52,762 ERROR org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread  - Error while closing Pulsar reader org.apache.pulsar.client.api.PulsarClientException: java.lang.InterruptedException
2020-07-15 15:45:52,765 INFO  org.apache.flink.runtime.taskmanager.Task                     - Source: Custom Source -> Flat Map -> Map -> Sink: Unnamed (1/1) (6ed38ee2c0456a1c6cc6f9fff2ce0b46) switched from RUNNING to FAILED.
java.lang.RuntimeException: start message id beyond the last commit
	at org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.skipFirstMessageIfNeeded(ReaderThread.java:153)
	at org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.run(ReaderThread.java:98)
2020-07-15 15:45:52,765 INFO  org.apache.pulsar.client.impl.ConsumerImpl                    - [persistent://cd/dev/flink_gpp_come_1-partition-2] [gpp_come-reader-d9f531ffe6] Closed consumer
2020-07-15 15:45:52,766 INFO  org.apache.flink.runtime.taskmanager.Task                     - Freeing task resources for Source: Custom Source -> Flat Map -> Map -> Sink: Unnamed (1/1) (6ed38ee2c0456a1c6cc6f9fff2ce0b46).
2020-07-15 15:45:52,766 INFO  org.apache.flink.runtime.taskmanager.Task                     - Ensuring all FileSystem streams are closed for task Source: Custom Source -> Flat Map -> Map -> Sink: Unnamed (1/1) (6ed38ee2c0456a1c6cc6f9fff2ce0b46) [FAILED]
2020-07-15 15:45:52,766 INFO  org.apache.flink.runtime.taskexecutor.TaskExecutor            - Un-registering task and sending final execution state FAILED to JobManager for task Source: Custom Source -> Flat Map -> Map -> Sink: Unnamed(1/1) 6ed38ee2c0456a1c6cc6f9fff2ce0b46.
2020-07-15 15:46:02,146 WARN  org.apache.pulsar.client.impl.ConsumerImpl                    - [persistent://cd/dev/flink_gpp_come_1-partition-1][gpp_come-reader-f1be7bfb17] Failed to subscribe to topic on 112.124.209.229/112.124.209.229:16656
2020-07-15 15:46:02,146 WARN  org.apache.pulsar.client.impl.PulsarClientImpl                - [persistent://cd/dev/flink_gpp_come_1-partition-1] Failed to get create topic reader
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: 39 lookup request timedout after ms 30000
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:700)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.apache.pulsar.client.impl.ClientCnx.checkRequestTimeout(ClientCnx.java:1026)
	at org.apache.pulsar.client.impl.ClientCnx.lambda$channelActive$0(ClientCnx.java:187)
	at org.apache.pulsar.shade.io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at org.apache.pulsar.shade.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176)
	at org.apache.pulsar.shade.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: 39 lookup request timedout after ms 30000
	at org.apache.pulsar.client.impl.ClientCnx.checkRequestTimeout(ClientCnx.java:1025)
	... 10 more
2020-07-15 15:46:02,147 WARN  org.apache.pulsar.client.impl.ClientCnx                       - [id: 0xf19c64e0, L:/10.52.10.21:59634 - R:112.124.209.229/112.124.209.229:16656] request 39 timed out after 30000 ms
2020-07-15 15:46:02,147 WARN  org.apache.pulsar.client.impl.ConsumerImpl                    - [persistent://cd/dev/flink_gpp_come_1-partition-0][gpp_come-reader-fcce1ceb6e] Failed to subscribe to topic on 112.124.209.229/112.124.209.229:16656
2020-07-15 15:46:02,147 WARN  org.apache.pulsar.client.impl.PulsarClientImpl                - [persistent://cd/dev/flink_gpp_come_1-partition-0] Failed to get create topic reader
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: 41 lookup request timedout after ms 30000
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:700)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.apache.pulsar.client.impl.ClientCnx.checkRequestTimeout(ClientCnx.java:1026)
	at org.apache.pulsar.client.impl.ClientCnx.lambda$channelActive$0(ClientCnx.java:187)
	at org.apache.pulsar.shade.io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at org.apache.pulsar.shade.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176)
	at org.apache.pulsar.shade.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: 41 lookup request timedout after ms 30000
	at org.apache.pulsar.client.impl.ClientCnx.checkRequestTimeout(ClientCnx.java:1025)
	... 10 more

=============================================
I use pulsar-flink-connector_2.11-2.4.23 , this problem still exists.

2020-07-15 17:38:20,951 INFO  org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader  - Committing offset 698658:-1:0 to topic persistent://cd/dev/flink_gpp_come_1-partition-0
2020-07-15 17:38:20,966 INFO  org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader  - Cannot commit cursor offset %d since the topic 698658:-1:0 has been deleted during execution
2020-07-15 17:38:20,966 INFO  org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader  - Committing offset 698659:-1:1 to topic persistent://cd/dev/flink_gpp_come_1-partition-1
2020-07-15 17:38:20,976 INFO  org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader  - Cannot commit cursor offset %d since the topic 698659:-1:1 has been deleted during execution
2020-07-15 17:38:20,976 INFO  org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader  - Committing offset 698660:2:2 to topic persistent://cd/dev/flink_gpp_come_1-partition-2
2020-07-15 17:38:20,985 INFO  org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader  - Successfully committed offset 698660:2:2 to topic persistent://cd/dev/flink_gpp_come_1-partition-2
2020-07-15 17:38:23,536 WARN  org.apache.pulsar.client.impl.ConsumerImpl                    - [persistent://cd/dev/flink_gpp_come_1-partition-0][gpp_come-reader-7dbd7e0c82] Failed to subscribe to topic on 112.124.209.229/112.124.209.229:16656
2020-07-15 17:38:23,536 WARN  org.apache.pulsar.client.impl.PulsarClientImpl                - [persistent://cd/dev/flink_gpp_come_1-partition-0] Failed to get create topic reader
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: 33 lookup request timedout after ms 30000
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:700)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.apache.pulsar.client.impl.ClientCnx.checkRequestTimeout(ClientCnx.java:1026)
	at org.apache.pulsar.client.impl.ClientCnx.lambda$channelActive$0(ClientCnx.java:187)
	at org.apache.pulsar.shade.io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at org.apache.pulsar.shade.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176)
	at org.apache.pulsar.shade.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: 33 lookup request timedout after ms 30000
	at org.apache.pulsar.client.impl.ClientCnx.checkRequestTimeout(ClientCnx.java:1025)
	... 10 more
2020-07-15 17:38:23,536 WARN  org.apache.pulsar.client.impl.ClientCnx                       - [id: 0x51ad5f27, L:/10.52.10.22:50758 - R:112.124.209.229/112.124.209.229:16656] request 33 timed out after 30000 ms
2020-07-15 17:38:23,537 WARN  org.apache.pulsar.client.impl.ConsumerImpl                    - [persistent://cd/dev/flink_gpp_come_1-partition-1][gpp_come-reader-b549d31f3b] Failed to subscribe to topic on 112.124.209.229/112.124.209.229:16656
2020-07-15 17:38:23,537 WARN  org.apache.pulsar.client.impl.PulsarClientImpl                - [persistent://cd/dev/flink_gpp_come_1-partition-1] Failed to get create topic reader
java.util.concurrent.CompletionException: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: 34 lookup request timedout after ms 30000
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:700)
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
	at org.apache.pulsar.client.impl.ClientCnx.checkRequestTimeout(ClientCnx.java:1026)
	at org.apache.pulsar.client.impl.ClientCnx.lambda$channelActive$0(ClientCnx.java:187)
	at org.apache.pulsar.shade.io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at org.apache.pulsar.shade.io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176)
	at org.apache.pulsar.shade.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:387)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.pulsar.client.api.PulsarClientException$TimeoutException: 34 lookup request timedout after ms 30000
	at org.apache.pulsar.client.impl.ClientCnx.checkRequestTimeout(ClientCnx.java:1025)
	... 10 more

Looking forward to your reply , thank you.

**Comment by codelipenghui** [comment]
@jianyun8023 Could you please help double confirm if we should fix issue now?

**Comment by MasterYiDragon** [comment]
any updates? we meet this issue too.

**Comment by jianyun8023** [comment]
> any updates? we meet this issue too.

What version are you using now? The latest version has solved the problem.

Related Issues: https://github.com/streamnative/pulsar-flink/issues/355
