### ISSUE TITLE
[BUG]use this connector in flink 1.11.1 ,when i run flink stop -p jobid command ,the command will timeout, i cannot stop the job

### ISSUE THREAD

**Issue by lookhua** [streamnative/pulsar-flink#112]
**Describe the bug**
pulsar version is 2.6.0
flink version is 1.11.1
flink job is a source connector  job 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
```
2020-07-30 20:55:39
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Failed to remove cursor for persistent://public/default/person-flink-test-topic
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.quiesceTimeServiceAndCloseOperator(StreamOperatorWrapper.java:161)
	at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.close(StreamOperatorWrapper.java:130)
	at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.close(StreamOperatorWrapper.java:80)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.closeOperators(OperatorChain.java:302)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.afterInvoke(StreamTask.java:567)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:538)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: Failed to remove cursor for persistent://public/default/person-flink-test-topic
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:616)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.close(FlinkPulsarSource.java:578)
	at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.close(AbstractUdfStreamOperator.java:109)
	at org.apache.flink.streaming.api.operators.StreamSource.close(StreamSource.java:130)
	at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.lambda$closeOperator$5(StreamOperatorWrapper.java:205)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:92)
	at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.closeOperator(StreamOperatorWrapper.java:203)
	at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.lambda$deferCloseOperatorToMailbox$3(StreamOperatorWrapper.java:177)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:92)
	at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:78)
	at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxExecutorImpl.tryYield(MailboxExecutorImpl.java:91)
	at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.quiesceTimeServiceAndCloseOperator(StreamOperatorWrapper.java:155)
	... 8 more
Caused by: java.lang.RuntimeException: Failed to remove cursor for persistent://public/default/person-flink-test-topic
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:281)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.cancel(PulsarFetcher.java:429)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:613)
	... 20 more
Caused by: java.lang.IllegalStateException: Client instance has been closed.
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyClient.checkNotClosed(JerseyClient.java:327)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.checkNotClosed(JerseyWebTarget.java:140)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:151)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.topicPath(TopicsImpl.java:962)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscriptionAsync(TopicsImpl.java:640)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscription(TopicsImpl.java:625)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:274)
	... 22 more
```

**Comment by jianyun8023** [comment]
moved #203
