### ISSUE TITLE
 Failed to get schema for source with exception java.lang.NullPointerException

### ISSUE THREAD

**Issue by holmes07** [streamnative/pulsar-flink#148]
**Describe the bug**
[ERROR] 2020-10-15 17:45:21,069 [FlinkPulsarRowSource] [getDeserializer:87] Failed to get schema for source with exception java.lang.NullPointerException
	at org.apache.flink.streaming.connectors.pulsar.internal.JacksonRecordParser.<init>(JacksonRecordParser.java:65)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarDeserializer.<init>(PulsarDeserializer.java:133)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarRowSource.getDeserializer(FlinkPulsarRowSource.java:82)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarRowSource.getProducedType(FlinkPulsarRowSource.java:68)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.getTypeInfo(StreamExecutionEnvironment.java:2172)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1608)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1569)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1551)

**To Reproduce**
![企业微信截图_16027562701405](https://user-images.githubusercontent.com/5210343/96109147-f0df6e00-0f10-11eb-90bf-677b77e3f3d4.png)

**solution ?**
Classs:FlinkPulsarRowSource
![企业微信截图_16027564543377](https://user-images.githubusercontent.com/5210343/96109588-5fbcc700-0f11-11eb-8239-e159eb61c7dd.png)

can i solve this by just pass a new JSONOptions(null,'','') here?

**Comment by xiaoyan5686670** [comment]
Yes, I also encountered this problem. Did you solve it?

**Comment by reswqa** [comment]
Thank you for discovering this problem and we have fixed it now.
