### ISSUE TITLE
[BUG] non serializable fields

### ISSUE THREAD

**Issue by holmes07** [streamnative/pulsar-flink#169]
**maven dependency
<groupId>io.streamnative.connectors</groupId>
  <artifactId>pulsar-flink-2.11-1.11.1</artifactId>
 <version>2.5.5</version>**

case : pulsar on flink sql 

Exception in thread "main" org.apache.flink.api.common.InvalidProgramException: The implementation of the FlinkPulsarSource is not serializable. The object probably contains or references non serializable fields.
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:151)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:71)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.clean(StreamExecutionEnvironment.java:1899)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1612)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1569)
	at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.addSource(StreamExecutionEnvironment.java:1551)
	at org.apache.flink.streaming.connectors.pulsar.PulsarTableSource.getDataStream(PulsarTableSource.java:200)
	at org.apache.flink.table.planner.plan.nodes.physical.PhysicalLegacyTableSourceScan.getSourceTransformation(PhysicalLegacyTableSourceScan.scala:82)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecLegacyTableSourceScan.translateToPlanInternal(StreamExecLegacyTableSourceScan.scala:98)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecLegacyTableSourceScan.translateToPlanInternal(StreamExecLegacyTableSourceScan.scala:63)
	at org.apache.flink.table.planner.plan.nodes.exec.ExecNode$class.translateToPlan(ExecNode.scala:58)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecLegacyTableSourceScan.translateToPlan(StreamExecLegacyTableSourceScan.scala:63)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecLegacySink.translateToTransformation(StreamExecLegacySink.scala:158)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecLegacySink.translateToPlanInternal(StreamExecLegacySink.scala:106)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecLegacySink.translateToPlanInternal(StreamExecLegacySink.scala:48)
	at org.apache.flink.table.planner.plan.nodes.exec.ExecNode$class.translateToPlan(ExecNode.scala:58)
	at org.apache.flink.table.planner.plan.nodes.physical.stream.StreamExecLegacySink.translateToPlan(StreamExecLegacySink.scala:48)
	at org.apache.flink.table.planner.delegation.StreamPlanner$$anonfun$translateToPlan$1.apply(StreamPlanner.scala:67)
	at org.apache.flink.table.planner.delegation.StreamPlanner$$anonfun$translateToPlan$1.apply(StreamPlanner.scala:66)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at org.apache.flink.table.planner.delegation.StreamPlanner.translateToPlan(StreamPlanner.scala:66)
	at org.apache.flink.table.planner.delegation.PlannerBase.translate(PlannerBase.scala:166)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.translate(TableEnvironmentImpl.java:1264)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeInternal(TableEnvironmentImpl.java:733)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeOperation(TableEnvironmentImpl.java:1069)
	at org.apache.flink.table.api.internal.TableEnvironmentImpl.executeSql(TableEnvironmentImpl.java:690)
	at PulsarFlinkSQLDemo.main(PulsarFlinkSQLDemo.java:38)
Caused by: java.io.NotSerializableException: org.apache.flink.streaming.connectors.pulsar.internal.JacksonRecordParser$FailureSafeRecordParser
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1185)
	at java.base/java.io.ObjectOutputStream.writeArray(ObjectOutputStream.java:1379)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1175)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1553)
	at java.base/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1510)
	at java.base/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1433)
	at java.base/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1179)
	at java.base/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:349)
	at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:586)
	at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:133)
	... 33 more

**Comment by jianyun8023** [comment]
Can you provide a reproduced code?

**Comment by holmes07** [comment]
> Can you provide a reproduced code?

import org.apache.flink.streaming.api.environment.StreamExecutionEnvironment;
import org.apache.flink.table.api.TableResult;
import org.apache.flink.table.api.bridge.java.StreamTableEnvironment;

public class PulsarFlinkSQLDemo {

    public static void main(String[] args) {

        StreamExecutionEnvironment see = StreamExecutionEnvironment.createLocalEnvironment();
        see.setParallelism(1);
        StreamTableEnvironment tEnv = StreamTableEnvironment.create(see);

        TableResult t1 = tEnv.executeSql("create table test_flink_sql(\n" +
                "`name` VARCHAR,\n" +
                "`uid` bigint\n" +
                ") with (\n" +
                "'connector.type' ='pulsar',\n" +
                "'connector.version' = '1',\n" +
                "'connector.topic' ='persistent://public/default/test_flink_sql',\n" +
                "'connector.service-url' ='pulsar://localhost:6650',\n" +
                "'connector.admin-url' ='http://localhost:8080',\n" +
                "'connector.startup-mode' ='external-subscription',\n" +
                "'connector.sub-name' ='test_flink_sql_v1',\n" +
                "'connector.properties.0.key' ='pulsar.reader.readerName',\n" +
                "'connector.properties.0.value' ='test_flink_sql_v1',\n" +
                "'connector.properties.1.key' ='pulsar.reader.subscriptionRolePrefix',\n" +
                "'connector.properties.1.value' ='test_flink_sql_v1',\n" +
                "'connector.properties.2.key' ='pulsar.reader.receiverQueueSize',\n" +
                "'connector.properties.2.value' = '1000',\n" +
                "'connector.properties.3.key' ='partitiondiscoveryintervalmillis',\n" +
                "'connector.properties.3.value' = '5000',\n" +
                "'format.type' ='json',\n" +
                "'format.derive-schema' ='true',\n" +
                "'format.ignore-parse-errors' ='true',\n" +
                "'update-mode' ='append'\n" +
                ")");
        t1.print();
        TableResult t2 = tEnv.executeSql(//"insert into test_flink_sql\n" +
                "select\n" +
                "name, uid\n" +
                "from test_flink_sql");
        t2.print();
//        see.execute();
    }
}

**Comment by reswqa** [comment]
We're sorry, but our example was not up to date and misled you. The 'format.ignore-parse-errors' = 'true' configuration option should not be used here.

**Comment by holmes07** [comment]
> We're sorry, but our example was not up to date and misled you. The 'format.ignore-parse-errors' = 'true' configuration option should not be used here.

I delete this 'format.ignore-parse-errors' = 'true'  conf and try it again , The problem is still there 。。

**Comment by reswqa** [comment]
Still experiencing serialization problems? I can't reproduce your same problem on my computer.

**Comment by holmes07** [comment]
> Still experiencing serialization problems? I can't reproduce your same problem on my computer.

here is my depedency , is there any different ？
you user verion             <version>2.5.5</version> to reproduce ??


 <properties>
        <pulsar.version>2.5.2</pulsar.version>
        <scala.binary.version>2.11</scala.binary.version>
        <flink.version>1.11.1</flink.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-log4j12</artifactId>
            <version>1.7.30</version>
        </dependency>

        <dependency>
            <groupId>org.apache.pulsar</groupId>
            <artifactId>pulsar-client</artifactId>
            <version>${pulsar.version}</version>
        </dependency>

        
        <dependency>
            <groupId>com.huya.beelogsvr</groupId>
            <artifactId>protocol</artifactId>
            <version>1.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.commons</groupId>
                    <artifactId>commons-lang3</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-api-java-bridge_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-planner-blink_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-streaming-scala_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-table-common</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <dependency>
            <groupId>org.apache.flink</groupId>
            <artifactId>flink-clients_2.11</artifactId>
            <version>${flink.version}</version>
        </dependency>

        <dependency>
            <groupId>io.streamnative.connectors</groupId>
            <artifactId>pulsar-flink-2.11-1.11.1</artifactId>

            <version>2.5.5</version>
        </dependency>

    </dependencies>

**Comment by reswqa** [comment]
I'm so sorry to tell you that our formal version have some problems in SQL. we have already fixed it, and plan to release new version in this weekend. Thanks for your feekback.

**Comment by holmes07** [comment]
> I'm so sorry to tell you that our formal version have some problems in SQL. we have already fixed it, and plan to release new version in this weekend. Thanks for your feekback.

hi  ,
Is the new version released?
