### ISSUE TITLE
[BUG] Possible memory lead

### ISSUE THREAD

**Issue by roee-hershko** [streamnative/pulsar-flink#170]
**Describe the bug**
When Flink job fails using as pulsar as a source, re-creating the job causes flink error:
```
2020-11-14 18:38:53
org.apache.flink.runtime.JobException: Recovery is suppressed by FixedDelayRestartBackoffTimeStrategy(maxNumberRestartAttempts=4, backoffTimeMS=10000)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.handleFailure(ExecutionFailureHandler.java:116)
	at org.apache.flink.runtime.executiongraph.failover.flip1.ExecutionFailureHandler.getFailureHandlingResult(ExecutionFailureHandler.java:78)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.handleTaskFailure(DefaultScheduler.java:192)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.maybeHandleTaskFailure(DefaultScheduler.java:185)
	at org.apache.flink.runtime.scheduler.DefaultScheduler.updateTaskExecutionStateInternal(DefaultScheduler.java:179)
	at org.apache.flink.runtime.scheduler.SchedulerBase.updateTaskExecutionState(SchedulerBase.java:503)
	at org.apache.flink.runtime.jobmaster.JobMaster.updateTaskExecutionState(JobMaster.java:386)
	at jdk.internal.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcInvocation(AkkaRpcActor.java:284)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleRpcMessage(AkkaRpcActor.java:199)
	at org.apache.flink.runtime.rpc.akka.FencedAkkaRpcActor.handleRpcMessage(FencedAkkaRpcActor.java:74)
	at org.apache.flink.runtime.rpc.akka.AkkaRpcActor.handleMessage(AkkaRpcActor.java:152)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:26)
	at akka.japi.pf.UnitCaseStatement.apply(CaseStatements.scala:21)
	at scala.PartialFunction$class.applyOrElse(PartialFunction.scala:123)
	at akka.japi.pf.UnitCaseStatement.applyOrElse(CaseStatements.scala:21)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:170)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at scala.PartialFunction$OrElse.applyOrElse(PartialFunction.scala:171)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:517)
	at akka.actor.AbstractActor.aroundReceive(AbstractActor.scala:225)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:592)
	at akka.actor.ActorCell.invoke(ActorCell.scala:561)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:258)
	at akka.dispatch.Mailbox.run(Mailbox.scala:225)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:235)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: org.apache.pulsar.client.admin.PulsarAdminException: org.apache.pulsar.shade.io.netty.handler.codec.EncoderException: java.lang.OutOfMemoryError: Direct buffer memory
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:228)
	at org.apache.pulsar.client.admin.internal.TopicsImpl$7.failed(TopicsImpl.java:324)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$4.failed(JerseyInvocation.java:1030)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime.processFailure(ClientRuntime.java:231)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime.access$100(ClientRuntime.java:85)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime$2.lambda$failure$1(ClientRuntime.java:183)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors$1.call(Errors.java:272)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors$1.call(Errors.java:268)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:268)
	at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:312)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime$2.failure(ClientRuntime.java:183)
	at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$3.onThrowable(AsyncHttpConnector.java:279)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.NettyResponseFuture.abort(NettyResponseFuture.java:277)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.request.WriteListener.abortOnThrowable(WriteListener.java:50)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.request.WriteListener.operationComplete(WriteListener.java:61)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.request.WriteCompleteListener.operationComplete(WriteCompleteListener.java:28)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.request.WriteCompleteListener.operationComplete(WriteCompleteListener.java:20)
	at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:183)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:95)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPromise.addListener(DefaultChannelPromise.java:30)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.request.NettyRequestSender.writeRequest(NettyRequestSender.java:421)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.channel.NettyConnectListener.writeRequest(NettyConnectListener.java:80)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.channel.NettyConnectListener.onSuccess(NettyConnectListener.java:156)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.channel.NettyChannelConnector$1.onSuccess(NettyChannelConnector.java:92)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:26)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.SimpleChannelFutureListener.operationComplete(SimpleChannelFutureListener.java:20)
	at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
	at org.apache.pulsar.shade.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:300)
	at org.apache.pulsar.shade.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:335)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:702)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at org.apache.pulsar.shade.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.pulsar.shade.io.netty.handler.codec.EncoderException: java.lang.OutOfMemoryError: Direct buffer memory
	at org.apache.pulsar.shade.io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:107)
	at org.apache.pulsar.shade.io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeWrite(AbstractChannelHandlerContext.java:709)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:792)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:702)
	at org.apache.pulsar.shade.io.netty.handler.stream.ChunkedWriteHandler.doFlush(ChunkedWriteHandler.java:300)
	at org.apache.pulsar.shade.io.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:132)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:750)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:765)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1020)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:299)
	at org.apache.pulsar.shade.org.asynchttpclient.netty.request.NettyRequestSender.writeRequest(NettyRequestSender.java:420)
	... 23 more
Caused by: java.lang.OutOfMemoryError: Direct buffer memory
	at java.base/java.nio.Bits.reserveMemory(Unknown Source)
	at java.base/java.nio.DirectByteBuffer.<init>(Unknown Source)
	at java.base/java.nio.ByteBuffer.allocateDirect(Unknown Source)
	at org.apache.pulsar.shade.io.netty.buffer.PoolArena$DirectArena.allocateDirect(PoolArena.java:758)
	at org.apache.pulsar.shade.io.netty.buffer.PoolArena$DirectArena.newChunk(PoolArena.java:734)
	at org.apache.pulsar.shade.io.netty.buffer.PoolArena.allocateNormal(PoolArena.java:245)
	at org.apache.pulsar.shade.io.netty.buffer.PoolArena.allocate(PoolArena.java:215)
	at org.apache.pulsar.shade.io.netty.buffer.PoolArena.allocate(PoolArena.java:147)
	at org.apache.pulsar.shade.io.netty.buffer.PooledByteBufAllocator.newDirectBuffer(PooledByteBufAllocator.java:356)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:187)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBufAllocator.directBuffer(AbstractByteBufAllocator.java:178)
	at org.apache.pulsar.shade.io.netty.buffer.AbstractByteBufAllocator.buffer(AbstractByteBufAllocator.java:115)
	at org.apache.pulsar.shade.io.netty.handler.codec.http.HttpObjectEncoder.encode(HttpObjectEncoder.java:93)
	at org.apache.pulsar.shade.io.netty.handler.codec.http.HttpClientCodec$Encoder.encode(HttpClientCodec.java:167)
	at org.apache.pulsar.shade.io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	... 37 more
```
the only way to overcome this is by manually restarting all the flink task managers, i checked the flink logs
and found this errors coming from pulsar:
```
2020-11-14 18:33:50.178 IST
16:33:50.178 [Source: Custom Source (2/12)] ERROR org.apache.flink.streaming.runtime.tasks.StreamTask - Error during disposal of stream operator.
Info
2020-11-14 18:33:50.178 IST
java.lang.RuntimeException: java.lang.RuntimeException: Failed to remove cursor for persistent://public/default/ad_events-partition-7 at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:616) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.close(FlinkPulsarSource.java:578) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43) ~[flink-dist_2.11-1.11.1.jar:1.11.1] at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:117) ~[flink-dist_2.11-1.11.1.jar:1.11.1] at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:703) [flink-dist_2.11-1.11.1.jar:1.11.1] at org.apache.flink.streaming.runtime.tasks.StreamTask.cleanUpInvoke(StreamTask.java:635) [flink-dist_2.11-1.11.1.jar:1.11.1] at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:542) [flink-dist_2.11-1.11.1.jar:1.11.1] at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721) [flink-dist_2.11-1.11.1.jar:1.11.1] at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546) [flink-dist_2.11-1.11.1.jar:1.11.1] at java.lang.Thread.run(Unknown Source) [?:?] Caused by: java.lang.RuntimeException: Failed to remove cursor for persistent://public/default/ad_events-partition-7 at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:281) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.cancel(PulsarFetcher.java:429) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:613) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] ... 9 more Caused by: java.lang.IllegalStateException: Client instance has been closed. at org.apache.pulsar.shade.org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyClient.checkNotClosed(JerseyClient.java:327) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.checkNotClosed(JerseyWebTarget.java:140) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:151) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.pulsar.client.admin.internal.TopicsImpl.topicPath(TopicsImpl.java:962) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscriptionAsync(TopicsImpl.java:640) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscription(TopicsImpl.java:625) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:274) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.cancel(PulsarFetcher.java:429) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:613) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] ... 9 more
Info
2020-11-14 18:33:50.181 IST
16:33:50.180 [Legacy Source Thread - Source: Custom Source (3/12)] ERROR org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher - Exception while shutting down reader threads
Info
2020-11-14 18:33:50.181 IST
org.apache.pulsar.client.api.PulsarClientException: java.lang.InterruptedException at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:845) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.pulsar.client.impl.ConsumerBase.close(ConsumerBase.java:459) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.pulsar.client.impl.ReaderImpl.close(ReaderImpl.java:143) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.cancel(ReaderThread.java:213) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.runFetchLoop(PulsarFetcher.java:317) [blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.runWithTopicsDiscovery(FlinkPulsarSource.java:533) [blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.run(FlinkPulsarSource.java:490) [blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100) [flink-dist_2.11-1.11.1.jar:1.11.1] at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63) [flink-dist_2.11-1.11.1.jar:1.11.1] at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:201) [flink-dist_2.11-1.11.1.jar:1.11.1] Caused by: java.lang.InterruptedException at java.util.concurrent.CompletableFuture.reportGet(Unknown Source) ~[?:?] at java.util.concurrent.CompletableFuture.get(Unknown Source) ~[?:?] at org.apache.pulsar.client.impl.ConsumerBase.close(ConsumerBase.java:457) ~[blob_p-2c9125d2735f9496411d13e7ecb6fa954af72d2b-d1807db77a36dff9850df2245734793b:?] ... 8 more
Info
2020-11-14 18:33:50.185 IST
16:33:50.180 [Source: Custom Source (1/12)] ERROR org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource - Failed to cancel the Pulsar Fetcher java.lang.RuntimeException: Failed to remove cursor for persistent://public/default/ad_events-partition-0
Info
2020-11-14 18:33:50.185 IST
at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:281)
Info
2020-11-14 18:33:50.185 IST
at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.cancel(PulsarFetcher.java:429)
Info
2020-11-14 18:33:50.185 IST
at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.cancel(FlinkPulsarSource.java:613)
Info
2020-11-14 18:33:50.185 IST
at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.close(FlinkPulsarSource.java:578)
Info
2020-11-14 18:33:50.185 IST
at org.apache.flink.api.common.functions.util.FunctionUtils.closeFunction(FunctionUtils.java:43)
Info
2020-11-14 18:33:50.185 IST
at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.dispose(AbstractUdfStreamOperator.java:117)
Info
2020-11-14 18:33:50.185 IST
at org.apache.flink.streaming.runtime.tasks.StreamTask.disposeAllOperators(StreamTask.java:703)
Info
2020-11-14 18:33:50.185 IST
at org.apache.flink.streaming.runtime.tasks.StreamTask.cleanUpInvoke(StreamTask.java:635)
Info
2020-11-14 18:33:50.185 IST
at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:542)
Info
2020-11-14 18:33:50.185 IST
at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721)
Info
2020-11-14 18:33:50.185 IST
at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546)
Info
2020-11-14 18:33:50.185 IST
at java.base/java.lang.Thread.run(Unknown Source)
Info
2020-11-14 18:33:50.185 IST
Caused by: java.lang.IllegalStateException: Client instance has been closed. at org.apache.pulsar.shade.org.glassfish.jersey.internal.guava.Preconditions.checkState(Preconditions.java:169) at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyClient.checkNotClosed(JerseyClient.java:327) at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.checkNotClosed(JerseyWebTarget.java:140) at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:151) at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyWebTarget.path(JerseyWebTarget.java:60) at org.apache.pulsar.client.admin.internal.TopicsImpl.topicPath(TopicsImpl.java:962) at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscriptionAsync(TopicsImpl.java:640) at org.apache.pulsar.client.admin.internal.TopicsImpl.deleteSubscription(TopicsImpl.java:625) at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.removeCursor(PulsarMetadataReader.java:274) ... 11 more
Info
2020-11-14 18:33:50.185 IST
```

**Additional context**
i am using pulsar with 3 brokers (16GB/4CPU each) and flink with 4 task managers (30GB/3cores)
my direct memory for flink is 1GB, i am not 100% sure this issue is in pulsar but this behaviour doesn't happen when
i change to kafka source

**Comment by jianyun8023** [comment]
Can you provide more information about the version?
