### ISSUE TITLE
[BUG] pulsarcatalog does not work with flink 1.11.2 sql client

### ISSUE THREAD

**Issue by Gurpartap** [streamnative/pulsar-flink#198]
```
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: conf/sql-client-defaults.yaml
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
  68   │ #==============================================================================
  69   │ # Catalogs
  70   │ #==============================================================================
  71   │
  72   │ # Define catalogs here.
  73   │
  74   │ catalogs:
  75   │   - name: pulsarcatalog
  76   │     type: pulsar
  77   │     default-database: tn/ns
  78   │     service-url: "pulsar://localhost:6650"
  79   │     admin-url: "http://localhost:8000"
  80   │
```
```
/usr/local/Cellar/apache-flink/1.11.2/libexec
> ./bin/sql-client.sh embedded --jar lib/pulsar-flink-connector-common-2.5.5.1.jar
No default environment specified.
Searching for '/usr/local/Cellar/apache-flink/1.11.2/libexec/conf/sql-client-defaults.yaml'...found.
Reading default environment from: file:/usr/local/Cellar/apache-flink/1.11.2/libexec/conf/sql-client-defaults.yaml
No session environment specified.


Exception in thread "main" org.apache.flink.table.client.SqlClientException: Unexpected exception. This is a bug. Please consider filing an issue.
	at org.apache.flink.table.client.SqlClient.main(SqlClient.java:213)
Caused by: org.apache.flink.table.client.gateway.SqlExecutionException: Could not create execution context.
	at org.apache.flink.table.client.gateway.local.ExecutionContext$Builder.build(ExecutionContext.java:870)
	at org.apache.flink.table.client.gateway.local.LocalExecutor.openSession(LocalExecutor.java:227)
	at org.apache.flink.table.client.SqlClient.start(SqlClient.java:108)
	at org.apache.flink.table.client.SqlClient.main(SqlClient.java:201)
Caused by: org.apache.flink.table.api.NoMatchingTableFactoryException: Could not find a suitable table factory for 'org.apache.flink.table.factories.CatalogFactory' in
the classpath.

Reason: Required context properties mismatch.

The following properties are requested:
admin-url=http://localhost:8000
default-database=tn/ns
service-url=pulsar://localhost:6650
type=pulsar

The following factories have been considered:
org.apache.flink.table.catalog.GenericInMemoryCatalogFactory
	at org.apache.flink.table.factories.TableFactoryService.filterByContext(TableFactoryService.java:322)
	at org.apache.flink.table.factories.TableFactoryService.filter(TableFactoryService.java:190)
	at org.apache.flink.table.factories.TableFactoryService.findSingleInternal(TableFactoryService.java:143)
	at org.apache.flink.table.factories.TableFactoryService.find(TableFactoryService.java:113)
	at org.apache.flink.table.client.gateway.local.ExecutionContext.createCatalog(ExecutionContext.java:377)
	at org.apache.flink.table.client.gateway.local.ExecutionContext.lambda$null$5(ExecutionContext.java:626)
	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
	at org.apache.flink.table.client.gateway.local.ExecutionContext.lambda$initializeCatalogs$6(ExecutionContext.java:625)
	at org.apache.flink.table.client.gateway.local.ExecutionContext.wrapClassLoader(ExecutionContext.java:264)
	at org.apache.flink.table.client.gateway.local.ExecutionContext.initializeCatalogs(ExecutionContext.java:624)
	at org.apache.flink.table.client.gateway.local.ExecutionContext.initializeTableEnvironment(ExecutionContext.java:523)
	at org.apache.flink.table.client.gateway.local.ExecutionContext.<init>(ExecutionContext.java:183)
	at org.apache.flink.table.client.gateway.local.ExecutionContext.<init>(ExecutionContext.java:136)
	at org.apache.flink.table.client.gateway.local.ExecutionContext$Builder.build(ExecutionContext.java:859)
	... 3 more
```

> pulsar-flink-connector-common-2.5.5.1.jar
> 
> flink --version
> Version: 1.11.2, Commit ID: fe36135
>
> java -version
> openjdk version "11.0.9" 2020-10-20
> OpenJDK Runtime Environment (build 11.0.9+11)
> OpenJDK 64-Bit Server VM (build 11.0.9+11, mixed mode)

**Comment by jianyun8023** [comment]
The version 2.5.5.1 package you are using has both common and connector modules that need to be introduced. There is a mistake here, putting the jar into the lib eliminates the need for the `--jar` parameter.

We recommend you to use version 2.5.6, It has only one package. we have optimized a lot of content and added more sql tests in this version.

[pulsar-flink-connector-2.12-1.11-2.5.6](https://dl.bintray.com/streamnative/maven/io/streamnative/connectors/pulsar-flink-connector-2.12-1.11/2.5.6/)

pulsarcatalog adds `format.type` configuration

```yaml
catalogs: 
   - name: pulsarcatalog
     type: pulsar
     default-database: public/default
     service-url: "pulsar://localhost:6650"
     admin-url: "http://localhost:8080"
     ## flink format type
     format.type: json
```
