### ISSUE TITLE
[BUG] NotSerializableException in submitting flink job

### ISSUE THREAD

**Issue by wuzhanpeng** [streamnative/pulsar-flink#237]
**Describe the bug**
`org.apache.pulsar.client.api.Schema` is not serializable and therefore it leads a `java.io.NotSerializableException` in `PulsarSerializationSchemaWrapper` when submitting a flink job.

**To Reproduce**
1. Flink Program
```java
.addSink(new FlinkPulsarSink<>(
        serviceUrl, adminUrl,
        Optional.of("XX"), props,
        new PulsarSerializationSchemaWrapper
                .Builder<>(new SimpleStringSchema())
                .useSpecialMode(Schema.BYTES)
                .build()
));
```
2. See error
```
org.apache.flink.client.program.ProgramInvocationException: The main method caused an error: org.apache.pulsar.client.impl.schema.BytesSchema@5c089b2f is not serializable. The object probably contains or ref
erences non serializable fields.
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:330) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.client.program.PackagedProgram.invokeInteractiveModeForExecution(PackagedProgram.java:198) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.client.ClientUtils.executeProgram(ClientUtils.java:114) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.client.cli.CliFrontend.executeProgram(CliFrontend.java:743) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.client.cli.CliFrontend.run(CliFrontend.java:242) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.client.cli.CliFrontend.parseAndRun(CliFrontend.java:971) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.client.cli.CliFrontend.lambda$main$10(CliFrontend.java:1047) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
        at javax.security.auth.Subject.doAs(Subject.java:422) [?:1.8.0_211]
        at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1730) [hadoop-common-3.1.1.3.1.0.0-78.jar:?]
        at org.apache.flink.runtime.security.contexts.HadoopSecurityContext.runSecured(HadoopSecurityContext.java:41) [flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.client.cli.CliFrontend.main(CliFrontend.java:1047) [flink-dist_2.12-1.12.0.jar:1.12.0]
Caused by: org.apache.flink.api.common.InvalidProgramException: org.apache.pulsar.client.impl.schema.BytesSchema@5c089b2f is not serializable. The object probably contains or references non serializable fields.
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:151) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:126) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:126) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:71) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.clean(StreamExecutionEnvironment.java:2034) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.streaming.api.datastream.DataStream.clean(DataStream.java:200) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.streaming.api.datastream.DataStream.addSink(DataStream.java:1301) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:316) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        ... 11 more
Caused by: java.io.NotSerializableException: org.apache.pulsar.client.impl.schema.BytesSchema
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184) ~[?:1.8.0_211]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348) ~[?:1.8.0_211]
        at org.apache.flink.util.InstantiationUtil.serializeObject(InstantiationUtil.java:586) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:133) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:126) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:126) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.api.java.ClosureCleaner.clean(ClosureCleaner.java:71) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.streaming.api.environment.StreamExecutionEnvironment.clean(StreamExecutionEnvironment.java:2034) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.streaming.api.datastream.DataStream.clean(DataStream.java:200) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at org.apache.flink.streaming.api.datastream.DataStream.addSink(DataStream.java:1301) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
        at org.apache.flink.client.program.PackagedProgram.callMainMethod(PackagedProgram.java:316) ~[flink-dist_2.12-1.12.0.jar:1.12.0]
        ... 11 more
```

**Expected behavior**
Succeed submitting flink job

**Comment by jianyun8023** [comment]
One is to add serialization to the Pulsar Schema interface, and the other is to deprecate the `PulsarSerializationSchemaWrapper .Builder().useSpecialMode(Schema.BYTES)` method in the connector.

What do you think? @wuzhanpeng @reswqa

**Comment by reswqa** [comment]
What we actually need is only SchemaInfo, and as I recall the fields of SchemaInfo are supposed to be serializable, but this class does not implement the serializable interface. We could also wrap a SerializableSchemaInfo to serialize it, if Pulsar won't let us modify it.Or if you have other ideas we can discuss them.

**Comment by shibd** [comment]
I can fix it. @jianyun8023
