### ISSUE TITLE
Observing exceptions that are leading to checkpoint timeout

### ISSUE THREAD

**Issue by MSShravan** [streamnative/pulsar-flink#263]
Observing below 3 exceptions, as a consequence, checkpointing is getting timed out and flink fails to trigger a checkpoint/savepoint. This anyway keeps the Flink job in running state. This is generally observed with windowed transformations and also with more than 3 running pipelines.
We are using flink 1.11.3, flink-pulsar connector 2.12-1.11-2.5.6.1, and pulsar 2.7 in our environment.

2021-03-11 07:39:09.485 [Window(SlidingEventTimeWindows(5000, 5000), EventTimeTrigger, AggregateWindowFunction, AggregateMvgAvgProcessWindowFunction) -> (Moving_Average_Transform_monitoring, JsonNode_to_String -> (dp_moving_average_dest_data_topic6_monitoring, Sink: dp_moving_average_dest_data_topic6)) (7/8)] ERROR o.a.flink.streaming.connectors.pulsar.FlinkPulsarSinkBase  - Error while sending message to Pulsar: org.apache.pulsar.client.api.PulsarClientException$AlreadyClosedException: Producer already closed
        at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendAsync(PartitionedProducerImpl.java:172)
        at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:95)
        at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSink.invoke(FlinkPulsarSink.java:104)
        at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:56)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:717)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:692)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:672)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$BroadcastingOutputCollector.collect(OperatorChain.java:787)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$BroadcastingOutputCollector.collect(OperatorChain.java:740)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:52)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:30)
        at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:53)
        at com.hpe.itomdi.preload.PreloadUtils$2.flatMap(PreloadUtils.java:171)
        at com.hpe.itomdi.preload.PreloadUtils$2.flatMap(PreloadUtils.java:163)
        at org.apache.flink.streaming.api.operators.StreamFlatMap.processElement(StreamFlatMap.java:50)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:717)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:692)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:672)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$BroadcastingOutputCollector.collect(OperatorChain.java:787)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$BroadcastingOutputCollector.collect(OperatorChain.java:740)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:52)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:30)
        at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:53)
        at com.swgrp.itomdi.pipeline.node.transformation.compound.movingaverage.AggregateMvgAvgProcessWindowFunction.process(AggregateMvgAvgProcessWindowFunction.java:43)
        at com.swgrp.itomdi.pipeline.node.transformation.compound.movingaverage.AggregateMvgAvgProcessWindowFunction.process(AggregateMvgAvgProcessWindowFunction.java:14)
        at org.apache.flink.streaming.runtime.operators.windowing.functions.InternalSingleValueProcessWindowFunction.process(InternalSingleValueProcessWindowFunction.java:53)
        at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.emitWindowContents(WindowOperator.java:549)
        at org.apache.flink.streaming.runtime.operators.windowing.WindowOperator.onEventTime(WindowOperator.java:457)
        at org.apache.flink.streaming.api.operators.InternalTimerServiceImpl.advanceWatermark(InternalTimerServiceImpl.java:276)
        at org.apache.flink.streaming.api.operators.InternalTimeServiceManager.advanceWatermark(InternalTimeServiceManager.java:154)
        at org.apache.flink.streaming.api.operators.AbstractStreamOperator.processWatermark(AbstractStreamOperator.java:593)
        at org.apache.flink.streaming.runtime.tasks.OneInputStreamTask$StreamTaskNetworkOutput.emitWatermark(OneInputStreamTask.java:167)
        at org.apache.flink.streaming.runtime.streamstatus.StatusWatermarkValve.findAndOutputNewMinWatermarkAcrossAlignedChannels(StatusWatermarkValve.java:179)
        at org.apache.flink.streaming.runtime.streamstatus.StatusWatermarkValve.inputWatermark(StatusWatermarkValve.java:101)
        at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.processElement(StreamTaskNetworkInput.java:180)
        at org.apache.flink.streaming.runtime.io.StreamTaskNetworkInput.emitNext(StreamTaskNetworkInput.java:153)
        at org.apache.flink.streaming.runtime.io.StreamOneInputProcessor.processInput(StreamOneInputProcessor.java:67)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.processInput(StreamTask.java:351)
        at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:185)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:569)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:534)
        at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546)
        at java.lang.Thread.run(Thread.java:748)

-----------------------------------

2021-03-11 07:25:35.682 [Legacy Source Thread - Source: multisrc1,multisrc2,multisrc3,multisrc4,multisrc5,multisrc6,multisrc7,multisrc8,multisrc9,multisrc10,multisrc11,multisrc12,multisrc13,multisrc14,multisrc15,multisrc16,multisrc17,multisrc18,multisrc19,multisrc20 -> (multisrc1,multisrc2,multisrc3,multisrc4,multisrc5,multisrc6,multisrc7,multisrc8,multisrc9,multisrc10,multisrc11,multisrc12,multisrc13,multisrc14,multisrc15,multisrc16,multisrc17,multisrc18,multisrc19,multisrc20_monitoring, invalid_data_topic_monitoring, Sink: invalid_data_topic, String_to_JsonNode -> Multi_Src_Single_Sink_Custom_Transform.Transform -> (Transform_transformation, JsonNode_to_String -> (valid_data_topic_monitoring, Sink: valid_data_topic))) (2/8)] ERROR o.a.flink.streaming.connectors.pulsar.internal.ReaderThread  - failed to close reader.
org.apache.pulsar.client.api.PulsarClientException: java.lang.InterruptedException
        at org.apache.pulsar.client.api.PulsarClientException.unwrap(PulsarClientException.java:845)
        at org.apache.pulsar.client.impl.ConsumerBase.close(ConsumerBase.java:435)
        at org.apache.pulsar.client.impl.ReaderImpl.close(ReaderImpl.java:143)
        at org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.cancel(ReaderThread.java:212)
        at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.runFetchLoop(PulsarFetcher.java:312)
        at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.run(FlinkPulsarSource.java:486)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:100)
        at org.apache.flink.streaming.api.operators.StreamSource.run(StreamSource.java:63)
        at org.apache.flink.streaming.runtime.tasks.SourceStreamTask$LegacySourceFunctionThread.run(SourceStreamTask.java:213)
Caused by: java.lang.InterruptedException: null
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:347)
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
        at org.apache.pulsar.client.impl.ConsumerBase.close(ConsumerBase.java:433)
        ... 7 common frames omitted

---------------------------------

2021-03-11 07:34:05.636 [pulsar-timer-2518-1] ERROR o.a.p.s.i.n.util.concurrent.DefaultPromise.rejectedExecution  - Failed to submit a listener notification task. Event loop shut down?
java.util.concurrent.RejectedExecutionException: event executor terminated
        at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
        at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
        at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
        at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
        at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818)
        at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.safeExecute(DefaultPromise.java:841)
        at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:498)
        at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:183)
        at org.apache.pulsar.shade.io.netty.util.concurrent.DefaultPromise.addListener(DefaultPromise.java:35)
        at org.apache.pulsar.client.impl.ConnectionPool.resolveName(ConnectionPool.java:275)
        at org.apache.pulsar.client.impl.ConnectionPool.createConnection(ConnectionPool.java:233)
        at org.apache.pulsar.client.impl.ConnectionPool.createConnection(ConnectionPool.java:167)
        at org.apache.pulsar.client.impl.ConnectionPool.lambda$getConnection$4(ConnectionPool.java:155)
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
        at org.apache.pulsar.client.impl.ConnectionPool.getConnection(ConnectionPool.java:155)
        at org.apache.pulsar.client.impl.ConnectionPool.getConnection(ConnectionPool.java:106)
        at org.apache.pulsar.client.impl.BinaryProtoLookupService.findBroker(BinaryProtoLookupService.java:110)
        at org.apache.pulsar.client.impl.BinaryProtoLookupService.getBroker(BinaryProtoLookupService.java:89)
        at org.apache.pulsar.client.impl.PulsarClientImpl.getConnection(PulsarClientImpl.java:612)
        at org.apache.pulsar.client.impl.ConnectionHandler.grabCnx(ConnectionHandler.java:67)
        at org.apache.pulsar.client.impl.ConnectionHandler.lambda$reconnectLater$1(ConnectionHandler.java:107)
        at org.apache.pulsar.shade.io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:672)
        at org.apache.pulsar.shade.io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:747)
        at org.apache.pulsar.shade.io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:472)
        at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Comment by jianyun8023** [comment]
@MSShravan Will this problem still occur after the new migration solution is validated?

**Comment by MSShravan** [comment]
@jianyun8023 I haven't observed this issue on a fresh start of Flink job. This issue is observed on multiple restarts of Flink job, the job is restarted when a new pipeline is added.

**Comment by jianyun8023** [comment]
> @jianyun8023 I haven't observed this issue on a fresh start of Flink job. This issue is observed after multiple restarts of Flink job, the job is restarted when a new pipeline is added.
@MSShravan 
Is flink taskmanger running all the time, or will taskmanger be created every time a flink job is created?

**Comment by MSShravan** [comment]
@jianyun8023 taskmanager java process will be in running state all the time but it will have no tasks running as Flink job will not be running between restarts of Flink job, once Flink job is up and running, taskmanager will have its tasks also running

**Comment by jianyun8023** [comment]
@MSShravan Can you see the abnormality of the task on the flink jobmanger ui? These exceptions are not root exceptions. I suspect it may be related to thread remnants, like #267.

**Comment by jianyun8023** [comment]
@MSShravan Have you set the size of `clientcachesize`? A known problem is that the instance of pulsar client will be created repeatedly because the `Authentication` does not implement the equals method.
