### ISSUE TITLE
Got exception java.lang.NoSuchFieldError: 

### ISSUE THREAD

**Issue by gaozhangmin** [streamnative/pulsar-flink#288]
**Describe the bug**
first connected to pulsar : got error
021-03-31 14:49:43,681 WARN  org.apache.pulsar.client.impl.ClientCnx                      [] - [x.x.x.x/x.x.x.x:6650] Got exception java.lang.NoSuchFieldError: INIT_AUTH_DATA
	at org.apache.pulsar.client.impl.ClientCnx.newConnectCommand(ClientCnx.java:229)
	at org.apache.pulsar.client.impl.ClientCnx.channelActive(ClientCnx.java:210)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:209)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1398)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:230)
	at org.apache.pulsar.shade.io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:216)
	at org.apache.pulsar.shade.io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:895)
	at org.apache.pulsar.shade.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:620)
	at org.apache.pulsar.shade.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:653)
	at org.apache.pulsar.shade.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:529)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:465)
	at org.apache.pulsar.shade.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
	at org.apache.pulsar.shade.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at org.apache.pulsar.shade.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at org.apache.pulsar.shade.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)

2021-03-31 14:49:43,682 INFO  org.apache.pulsar.client.impl.ClientCnx                      [] - [id: 0xf7674126, L:/x.x.x.x:46312 ! R:x.x.x.x/x.x.x.x:6650] Disconnected
2021-03-31 14:49:43,684 WARN  org.apache.pulsar.client.impl.ConnectionPool                 [] - [[id: 0xf7674126, L:/x.x.x.x:46312 ! R:x.x.x.x/x.x.x.x:6650]] Connection handshake failed: org.apache.pulsar.client.api.PulsarClientException: Connection already closed
2021-03-31 14:49:43,786 WARN  org.apache.pulsar.client.impl.PulsarClientImpl               [] - [topic: persistent://public/default/1p] Could not get connection while getPartitionedTopicMetadata -- Will try again in 100 ms

**Comment by jianyun8023** [comment]
Please provide flink version, pulsar version and pulsar flink connector version.

**Comment by gaozhangmin** [comment]
> Please provide flink version, pulsar version and pulsar flink connector version.

flink 1.12,   pulsar 2.7.0, connector copied from master branch

**Comment by gaozhangmin** [comment]
branch 2.7.4  worked. but master branch cannot

**Comment by syhily** [comment]
New master branch should contain this bugfix?
