### ISSUE TITLE
issue while backup and restore from savepoint

### ISSUE THREAD

**Issue by Debashish-Mallick** [streamnative/pulsar-flink#300]
This is regarding backup restore . We are not taking any LPV backup. While restore the old LPV won't be present. We are taking savepoint backup ,while restoring getting below exception from flink connector. 
Connector should take offset from savepoint (which is backed up) and process.

Flink version used **1.9.3**, pulsar-flink-connector_2.11-**2.4.28.3** and pulsar **2.6**

**Log:**
2021-04-05 08:32:05.894 [Async calls on Source: src5 -> (src5_monitoring, invalid_data_topic_monitoring, Sink: invalid_data_topic, String_to_JsonNode -> Timestamps/Watermarks) (7/8)] WARN  o.a.flink.streaming.connectors.pulsar.internal.PulsarFetcher  - **Failed to commit cursor to Pulsar.**
java.lang.RuntimeException: **Failed to commit cursor offset 13086:38:0:0** for persistent://public/default/src5-partition-0
                    at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.commitCursorToOffset(PulsarMetadataReader.java:263)
                    at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.doCommitOffsetToPulsar(PulsarFetcher.java:452)
                    at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.commitOffsetToPulsar(PulsarFetcher.java:440)
                    at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.notifyCheckpointComplete(FlinkPulsarSource.java:742)
                    at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.notifyCheckpointComplete(AbstractUdfStreamOperator.java:130)
                    at org.apache.flink.streaming.runtime.tasks.StreamTask.notifyCheckpointComplete(StreamTask.java:842)
                    at org.apache.flink.runtime.taskmanager.Task$2.run(Task.java:1214)
                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.pulsar.client.admin.PulsarAdminException: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_128,128,356740187) has been shut down
                    at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:228)
                    at org.apache.pulsar.client.admin.internal.TopicsImpl.resetCursor(TopicsImpl.java:864)
                    at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.commitCursorToOffset(PulsarMetadataReader.java:253)
                    ... 11 common frames omitted
Caused by: org.apache.pulsar.shade.org.glassfish.hk2.api.MultiException: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_128,128,356740187) has been shut down
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:106)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.FactoryCreator.dispose(FactoryCreator.java:173)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:542)
                    at org.apache.pulsar.shade.org.glassfish.jersey.inject.hk2.RequestContext.lambda$findOrCreate$0(RequestContext.java:84)
                    at org.apache.pulsar.shade.org.glassfish.jersey.internal.inject.ForeignDescriptorImpl.dispose(ForeignDescriptorImpl.java:87)
                    at org.apache.pulsar.shade.org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance.remove(Hk2RequestScope.java:150)
                    at java.lang.Iterable.forEach(Iterable.java:75)
                    at org.apache.pulsar.shade.org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance.release(Hk2RequestScope.java:167)
                    at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.release(RequestScope.java:270)
                    at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:416)
                    at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
                    at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
                    at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
                    at org.apache.pulsar.client.admin.internal.TopicsImpl.resetCursor(TopicsImpl.java:861)
                    ... 12 common frames omitted
Caused by: java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_128,128,356740187) has been shut down
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2393)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandleImpl(ServiceLocatorImpl.java:635)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:628)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:646)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:103)
                    ... 25 common frames omitted

**Comment by jianyun8023** [comment]
Can you provide information about your runtime environment? And the list of jars used. This error looks strange.

**Comment by Debashish-Mallick** [comment]
Hi Jia,
Details are sent via microfocus mail id. Thank you.

**Comment by jianyun8023** [comment]
According to the information in the log, it is the problem caused by the reset cursor error when recovering. From the log of the broker, the message corresponding to this cursor has been deleted in pulsar, and an error occurred while resetting the cursor.

**Comment by jianyun8023** [comment]
> According to the information in the log, it is the problem caused by the reset cursor error when recovering. From the log of the broker, the message corresponding to this cursor has been deleted in pulsar, and an error occurred while resetting the cursor.

After Pulsar's ledger is recycled, the new ledgerId will be smaller than the old ledgerId. When looking up the old ledgerId+1, the data will not be found. Here will print an error log, and then get the last ledger. Please don't be scared by this log, there is no problem with pulsar here.

**Comment by jianyun8023** [comment]
When restoring state, the pulsar cursor corresponding to the offset in the state may have failed. If it fails, it will cause the task to fail. You can use the configuration `pulsar.reader.failOnDataLoss=false` to skip the invalid cursor, and it will automatically find the next available cursor by the pulsar broker.
