### ISSUE TITLE
[BUG] NPE when getPositionFromSubscription

### ISSUE THREAD

**Issue by codelipenghui** [streamnative/pulsar-flink#301]
**Describe the bug**
```
2021-04-21 06:59:02.302 [flink-akka.actor.default-dispatcher-3] INFO  org.apache.flink.runtime.executiongraph.ExecutionGraph  - Source: public/default/test-src-topic-4 -> Map (6/8) (a19cde24389c57e370a6f8cc79a9fb86) switched from RUNNING to FAILED on 85eed6e35f97eb5d31d6852653c4c17e @ 172.16.1.31 (dataPort=36918).
java.lang.NullPointerException: null
        at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.getPositionFromSubscription(PulsarMetadataReader.java:279)
        at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.offsetForEachTopic(FlinkPulsarSource.java:773)
        at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.open(FlinkPulsarSource.java:372)
        at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
        at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:291)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$1(StreamTask.java:506)
        at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:92)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:475)
        at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:526)
        at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721)
        at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546)
        at java.lang.Thread.run(Thread.java:748)
```

Connector version: pulsar-flink-connector-2.12-1.11:2.5.6.1

**Comment by gaozhangmin** [comment]
please assign to me
