### ISSUE TITLE
Observing dataloss due to "Producer already closed" exceptions

### ISSUE THREAD

**Issue by MSShravan** [streamnative/pulsar-flink#302]
Observing dataloss due to "Producer already closed" exceptions as below

2021-04-17 18:29:37.393 [Pulsar Reader for TopicRange{topic=persistent://public/default/profile2_10-partition-0, key-range=SerializableRange{range=[0, 65535]}} in task Source: profile2_10 -> (profile2_10_monitoring, invalid_data_topic_monitoring, Sink: invalid_data_topic, String_to_JsonNode -> Kafka_TimestampTransform_Kafka_profile2_10.Transform -> (Transform_transformation, JsonNode_to_String -> (preload_profile2_10_monitoring, Sink: preload_profile2_10)))] **ERROR o.a.flink.streaming.connectors.pulsar.FlinkPulsarSinkBase  - Error while sending message to Pulsar: org.apache.pulsar.client.api.PulsarClientException$AlreadyClosedException: Producer already closed**
        at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendAsync(PartitionedProducerImpl.java:172)
        at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:95)
        at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSink.invoke(FlinkPulsarSink.java:104)
        at org.apache.flink.streaming.api.operators.StreamSink.processElement(StreamSink.java:56)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:717)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:692)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:672)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$BroadcastingOutputCollector.collect(OperatorChain.java:787)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$BroadcastingOutputCollector.collect(OperatorChain.java:740)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:52)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:30)
        at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:53)
        at com.hpe.itomdi.preload.PreloadUtils$2.flatMap(PreloadUtils.java:171)
        at com.hpe.itomdi.preload.PreloadUtils$2.flatMap(PreloadUtils.java:163)
        at org.apache.flink.streaming.api.operators.StreamFlatMap.processElement(StreamFlatMap.java:50)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:717)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:692)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:672)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$BroadcastingOutputCollector.collect(OperatorChain.java:787)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$BroadcastingOutputCollector.collect(OperatorChain.java:740)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:52)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:30)
        at org.apache.flink.streaming.api.operators.StreamMap.processElement(StreamMap.java:41)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:717)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:692)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:672)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:52)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:30)
        at org.apache.flink.streaming.api.operators.TimestampedCollector.collect(TimestampedCollector.java:53)
        at com.hpe.itomdi.preload.PreloadUtils$1.flatMap(PreloadUtils.java:140)
        at com.hpe.itomdi.preload.PreloadUtils$1.flatMap(PreloadUtils.java:126)
        at org.apache.flink.streaming.api.operators.StreamFlatMap.processElement(StreamFlatMap.java:50)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.pushToOperator(OperatorChain.java:717)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:692)
        at org.apache.flink.streaming.runtime.tasks.OperatorChain$CopyingChainingOutput.collect(OperatorChain.java:672)
        at org.apache.flink.streaming.api.collector.selector.DirectedOutput.collect(DirectedOutput.java:143)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:52)
        at org.apache.flink.streaming.api.operators.CountingOutput.collect(CountingOutput.java:30)
        at org.apache.flink.streaming.api.operators.StreamSourceContexts$ManualWatermarkContext.processAndCollect(StreamSourceContexts.java:305)
        at org.apache.flink.streaming.api.operators.StreamSourceContexts$WatermarkContext.collect(StreamSourceContexts.java:394)
        at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.emitRecord(PulsarFetcher.java:345)
        at org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.emitRecord(ReaderThread.java:204)
        at org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.run(ReaderThread.java:102)
        
        
Failed data push has to be retried instead of dropping.

**Comment by codelipenghui** [comment]
@jianyun8023 Please help take a look at this issue.

**Comment by syhily** [comment]
This is a known issue before version `1.12.2.1`, `1.11.1.0` and `1.9.3.0` release. We cached the pulsar-client instance in memory, but the cache key is not unique, this would cause the old client be closed and removed. If you use the old version, just bump your connector to the latest release.

**Comment by MSShravan** [comment]
@syhily couple of other fixes are provided on top of 2.5.8.4 version of connector. Can a fix for this issue be provided on this version of connector itself?

**Comment by syhily** [comment]
> @syhily couple of other fixes are provided on top of 2.5.8.4 version of connector. Can a fix for this issue be provided on this version of connector itself?

These known fixes are also included in the latest release, including the security fix. Maintain a historical package is a reasonable manner. So I recommend migrating to the latest connector.

**Comment by MSShravan** [comment]
@syhily Can you confirm if the latest version of connector for Flink 1.11.3 has fixes for https://github.com/streamnative/pulsar-flink/issues/256, https://github.com/streamnative/pulsar-flink/issues/271 issues?
Also what connector version would you recommend for a smooth upgrade from "_pulsar-flink-connector-2.12-1.11-2.5.8.4_" version?

Is it "_pulsar-flink-connector-2.12-1.11-2.7.1.1_" or any other version?

FYI, below is our running environment,

Flink - 1.11.3
Pulsar - 2.7
Connector - 2.12-1.11-2.5.8.4

**Comment by syhily** [comment]
> @syhily Can you confirm if the latest version of connector for Flink 1.11.3 has fixes for #256, #271 issues?
> Also what connector version would you recommend for a smooth upgrade from "_pulsar-flink-connector-2.12-1.11-2.5.8.4_" version?
> 
> Is it "_pulsar-flink-connector-2.12-1.11-2.7.1.1_" or any other version?
> 
> FYI, below is our running environment,
> 
> Flink - 1.11.3
> Pulsar - 2.7
> Connector - 2.12-1.11-2.5.8.4

Flink with scala 2.12? Using this version could fix. https://mvnrepository.com/artifact/io.streamnative.connectors/pulsar-flink-connector_2.12/1.11.1.0

**Comment by jianyun8023** [comment]
@MSShravan  You can upgrade to the new version [pulsar-flink-connector_2.12 1.11.1.0](https://mvnrepository.com/artifact/io.streamnative.connectors/pulsar-flink-connector_2.12/1.11.1.0), This version will no longer rely on all shades in the connector package, and you can flexibly control the dependencies you need according to your needs.

**Comment by MSShravan** [comment]
@jianyun8023, where can I get the connector jar as I need to bundle it in Flink lib directory?
Checked in https://repo1.maven.org/maven2/io/streamnative/connectors/pulsar-flink-connector_2.12/1.11.1.0/ but the connector jar size is only 44KB, it should be around 45MB, right?

**Comment by syhily** [comment]
> @jianyun8023, where can I get the connector jar as I need to bundle it in Flink lib directory?
> Checked in https://repo1.maven.org/maven2/io/streamnative/connectors/pulsar-flink-connector_2.12/1.11.1.0/ but the connector jar size is only 404KB, it should be around 45MB, right?

The new connector didn't provide the fat-jar, we exclude the pulsar-client-all out of the distributed jar. So you can define the pulsar-client version in your pom file.

**Comment by syhily** [comment]
Close for this issue has been fixed.
