### ISSUE TITLE
[BUG]Broker logs reported the error "307 temporary redirect" while restoring from a savepoint from backed up setup to a fresh setup

### ISSUE THREAD

**Issue by harish-bakthavachalam** [streamnative/pulsar-flink#304]
This is regarding backup restore .We are taking savepoint/checkpoint backup ,while restoring getting below exception from flink connector and pulsar broker.
we are using flink 1.11.3 and below connector version pulsar-flink-connector-2.12-1.11-2.5.6.1.jar
We are not taking any LPV backup. While restore the old LPV won't be present.
we have seen "reader-" subscription getting created for two partitions (topic-partition-0) and (topic-partition-2).
For the (topic-partition-1), it failed to reset cursor and thrown http internal server error (as seen in master/worker logs)  and it didn't create the subscription for it (checked using pulsar stats).
Broker logs reported the error "307 temporary redirect".
Seeing similar issue has been already in git.
https://github.com/apache/pulsar/issues/6121

broker log :

`10:54:56.154 [pulsar-web-47-6] INFO  org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [itom-di-message-bus-svc][persistent://public/default/preloadSrc-partition-2] Creating subscription itom-di-dp-preloadSrc at message id -1:-1:-1
10:54:56.188 [pulsar-web-47-7] INFO  org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [itom-di-message-bus-svc][persistent://public/default/preloadSrc-partition-0] Creating subscription itom-di-dp-preloadSrc at message id -1:-1:-1
10:54:56.188 [pulsar-web-47-7] WARN  org.apache.pulsar.broker.admin.impl.PersistentTopicsBase - [itom-di-message-bus-svc][persistent://public/default/preloadSrc-partition-0] Failed to create subscription itom-di-dp-preloadSrc at message id -1:-1:-1`

`javax.ws.rs.WebApplicationException: HTTP 307 Temporary Redirect
	at org.apache.pulsar.broker.web.PulsarWebResource.validateTopicOwnership(PulsarWebResource.java:635) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.validateAdminAccessForSubscriber(PersistentTopicsBase.java:297) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.internalCreateSubscriptionForNonPartitionedTopic(PersistentTopicsBase.java:1981) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
	at org.apache.pulsar.broker.admin.impl.PersistentTopicsBase.internalCreateSubscription(PersistentTopicsBase.java:1902) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
	at org.apache.pulsar.broker.admin.v2.PersistentTopics.createSubscription(PersistentTopics.java:1274) ~[org.apache.pulsar-pulsar-broker-2.7.0.jar:2.7.0]
	at sun.reflect.GeneratedMethodAccessor129.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_282]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_282]
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory.lambda$static$0(ResourceMethodInvocationHandlerFactory.java:52) ~[org.glassfish.jersey.core-jersey-server-2.31.jar:?]`

flink log:

`2021-04-21 11:10:04.833 [Source: preloadSrc -> (preloadSrc_monitoring, invalid_data_topic_monitoring, Sink: invalid_data_topic, String_to_JsonNode -> Pulsar_Custom_TimestampTransform_Pulsar.Transform -> (Transform_transformation, JsonNode_to_String -> (preload_monitoring, Sink: preload))) (6/8)] WARN  org.apache.flink.runtime.taskmanager.Task  - Source: preloadSrc -> (preloadSrc_monitoring, invalid_data_topic_monitoring, Sink: invalid_data_topic, String_to_JsonNode -> Pulsar_Custom_TimestampTransform_Pulsar.Transform -> (Transform_transformation, JsonNode_to_String -> (preload_monitoring, Sink: preload))) (6/8) (340276ae8781bf9107d44fb2af62cfc3) switched from RUNNING to FAILED.
java.lang.RuntimeException: org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: HTTP 500 Internal Server Error
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.resetCursor(PulsarMetadataReader.java:423)
	at org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.skipFirstMessageIfNeeded(ReaderThread.java:156)
	at org.apache.flink.streaming.connectors.pulsar.internal.ReaderThread.run(ReaderThread.java:95)
Caused by: org.apache.pulsar.client.admin.PulsarAdminException$ServerSideErrorException: HTTP 500 Internal Server Error
	at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:209)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.resetCursor(TopicsImpl.java:1121)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.resetCursor(PulsarMetadataReader.java:421)
	... 2 common frames omitted
Caused by: org.apache.pulsar.shade.javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1098)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:883)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:767)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:316)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:298)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:229)
	at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:414)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.resetCursor(TopicsImpl.java:1118)
	... 3 common frames omitted`

issue is seen on the Environment with below version :
`flink 1.11.3
pulsar broker 2.7.0
pulsar client 2.6.0-sn-18-2
pulsar-flink-connector-2.12-1.11-2.5.6.1.jar`
we have updated to `pulsar-flink-connector-2.12-1.11-2.5.8.4.`

**Comment by codelipenghui** [comment]
Is it related to #300 @jianyun8023

**Comment by jianyun8023** [comment]
I reviewed the log again, and it is the same problem as #300, because the program failed due to invalid offset. I will fix it at #319.

**Comment by syhily** [comment]
Close for resolved.
