### ISSUE TITLE
[BUG] Data loss occurring with message "Failed to commit cursor to Pulsar" in log

### ISSUE THREAD

**Issue by subbu107** [streamnative/pulsar-flink#317]
**Describe the bug**

Data loss seems to be occurring even if failonwrite is true. 
In this case, if pulsar sink write fails, the job restarts. However, we still find data loss occurring, but with a different exception

**To Reproduce**
1. Set up simple flink transformation with source, map transform and sink 
2. Continuously Stream data to source topic
3. Restart brokers randomly
 
**Expected behavior**
Data loss should not be happening in spite of temporary broker unavailability. As long as message is still available on broker, it should eventually get processed and written to sink.

Instead, we observe data loss at sink topic. 

Exception seen in logs is : 

2021-05-03 16:34:12.153 [Source: shravan_src -> (shravan_src_monitoring, invalid_data_topic_monitoring, Sink: invalid_data_topic, String_to_JsonNode -> pulsar_TimestampTransform.Transform -> (Transform_transformation, JsonNode_to_String -> (shravan_sink_monitoring, Sink: shravan_sink))) (8/8)] WARN  o.a.flink.streaming.connectors.pulsar.internal.PulsarFetcher  - Failed to commit cursor to Pulsar.
java.lang.RuntimeException: Failed to commit cursor for TopicRange{topic=persistent://public/default/shravan_src-partition-2, key-range=SerializableRange{range=[0, 65535]}}
               at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.commitCursorToOffset(PulsarMetadataReader.java:239)
               at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.doCommitOffsetToPulsar(PulsarFetcher.java:445)
               at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.commitOffsetToPulsar(PulsarFetcher.java:433)
               at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.notifyCheckpointComplete(FlinkPulsarSource.java:827)
               at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.notifyCheckpointComplete(AbstractUdfStreamOperator.java:130)
               at org.apache.flink.streaming.runtime.tasks.StreamOperatorWrapper.notifyCheckpointComplete(StreamOperatorWrapper.java:107)
               at org.apache.flink.streaming.runtime.tasks.SubtaskCheckpointCoordinatorImpl.notifyCheckpointComplete(SubtaskCheckpointCoordinatorImpl.java:283)
               at org.apache.flink.streaming.runtime.tasks.StreamTask.notifyCheckpointComplete(StreamTask.java:990)
               at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$notifyCheckpointCompleteAsync$10(StreamTask.java:961)
               at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$notifyCheckpointOperation$12(StreamTask.java:977)
               at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:92)
               at org.apache.flink.streaming.runtime.tasks.mailbox.Mail.run(Mail.java:78)
               at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.processMail(MailboxProcessor.java:301)
               at org.apache.flink.streaming.runtime.tasks.mailbox.MailboxProcessor.runMailboxLoop(MailboxProcessor.java:183)
               at org.apache.flink.streaming.runtime.tasks.StreamTask.runMailboxLoop(StreamTask.java:569)
               at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:534)
               at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:721)
               at org.apache.flink.runtime.taskmanager.Task.run(Task.java:546)
               at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.pulsar.client.admin.PulsarAdminException: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: itomdipulsar-broker
               at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:233)
               at org.apache.pulsar.client.admin.internal.BaseResource$2.failed(BaseResource.java:156)
               at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$1.failed(JerseyInvocation.java:839)
               at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime.processFailure(ClientRuntime.java:247)
               at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime.processFailure(ClientRuntime.java:242)
               at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime.access$100(ClientRuntime.java:62)
               at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime$2.lambda$failure$1(ClientRuntime.java:178)
               at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
               at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
               at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:292)
               at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:274)
               at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:244)
               at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
               at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime$2.failure(ClientRuntime.java:178)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$apply$1(AsyncHttpConnector.java:204)
               at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
               at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
               at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.apply(AsyncHttpConnector.java:202)
               at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime.lambda$null$6(ClientRuntime.java:182)
               at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
               at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
               at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:292)
               at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:274)
               at org.apache.pulsar.shade.org.glassfish.jersey.internal.Errors.process(Errors.java:244)
               at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:288)
               at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRuntime.lambda$createRunnableForAsyncProcessing$7(ClientRuntime.java:156)
               at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
               at java.util.concurrent.FutureTask.run(FutureTask.java:266)
               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
               ... 1 common frames omitted
Caused by: java.util.concurrent.CompletionException: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: itomdipulsar-broker
               at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
               at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
               at java.util.concurrent.CompletableFuture.orApply(CompletableFuture.java:1385)
               at java.util.concurrent.CompletableFuture.orApplyStage(CompletableFuture.java:1406)
               at java.util.concurrent.CompletableFuture.applyToEither(CompletableFuture.java:2089)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.retryOrTimeOut(AsyncHttpConnector.java:222)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.apply(AsyncHttpConnector.java:201)
               ... 13 common frames omitted
Caused by: org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector$RetryException: Could not complete the operation. Number of retries has been exhausted. Failed reason: itomdipulsar-broker
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$3(AsyncHttpConnector.java:248)
               at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
               at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
               at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.retryOperation(AsyncHttpConnector.java:233)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$3(AsyncHttpConnector.java:241)
               at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
               at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
               at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.retryOperation(AsyncHttpConnector.java:233)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$3(AsyncHttpConnector.java:241)
               at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
               at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
               at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.retryOperation(AsyncHttpConnector.java:233)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$3(AsyncHttpConnector.java:241)
               at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
               at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
               at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.retryOperation(AsyncHttpConnector.java:233)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$3(AsyncHttpConnector.java:241)
               at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
               at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
               at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.retryOperation(AsyncHttpConnector.java:233)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOperation$3(AsyncHttpConnector.java:241)
               at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:774)
               at java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:792)
               at java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2153)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.retryOperation(AsyncHttpConnector.java:233)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.retryOrTimeOut(AsyncHttpConnector.java:220)
               ... 14 common frames omitted
Caused by: java.net.UnknownHostException: itomdipulsar-broker
               at java.net.InetAddress.getAllByName0(InetAddress.java:1282)
               at java.net.InetAddress.getAllByName(InetAddress.java:1194)
               at java.net.InetAddress.getAllByName(InetAddress.java:1128)
               at org.apache.pulsar.shade.io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:169)
               at org.apache.pulsar.shade.io.netty.util.internal.SocketUtils$9.run(SocketUtils.java:166)
               at java.security.AccessController.doPrivileged(Native Method)
               at org.apache.pulsar.shade.io.netty.util.internal.SocketUtils.allAddressesByName(SocketUtils.java:166)
               at org.apache.pulsar.shade.io.netty.resolver.DefaultNameResolver.doResolveAll(DefaultNameResolver.java:50)
               at org.apache.pulsar.shade.io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:79)
               at org.apache.pulsar.shade.io.netty.resolver.SimpleNameResolver.resolveAll(SimpleNameResolver.java:71)
               at org.apache.pulsar.shade.org.asynchttpclient.resolver.RequestHostnameResolver.resolve(RequestHostnameResolver.java:50)
               at org.apache.pulsar.shade.org.asynchttpclient.netty.request.NettyRequestSender.resolveAddresses(NettyRequestSender.java:357)
               at org.apache.pulsar.shade.org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithNewChannel(NettyRequestSender.java:300)
               at org.apache.pulsar.shade.org.asynchttpclient.netty.request.NettyRequestSender.sendRequestWithCertainForceConnect(NettyRequestSender.java:142)
               at org.apache.pulsar.shade.org.asynchttpclient.netty.request.NettyRequestSender.sendRequest(NettyRequestSender.java:113)
               at org.apache.pulsar.shade.org.asynchttpclient.DefaultAsyncHttpClient.execute(DefaultAsyncHttpClient.java:259)
               at org.apache.pulsar.shade.org.asynchttpclient.DefaultAsyncHttpClient.executeRequest(DefaultAsyncHttpClient.java:228)
               at org.apache.pulsar.shade.org.asynchttpclient.BoundRequestBuilder.execute(BoundRequestBuilder.java:39)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.oneShot(AsyncHttpConnector.java:299)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.lambda$retryOrTimeOut$2(AsyncHttpConnector.java:220)
               at org.apache.pulsar.client.admin.internal.http.AsyncHttpConnector.retryOperation(AsyncHttpConnector.java:231)
               ... 40 common frames omitted

**Comment by syhily** [comment]
@jianyun8023 The cause for this issue is `java.net.UnknownHostException: itomdipulsar-broker`. Can you help me for debug the reason why pulsar-flink would connect to this host.

**Comment by jianyun8023** [comment]
Pulsar Sink relies on checkpoint. When `env.getCheckpointConfig().setTolerableCheckpointFailureNumber(2147483647)` is set, data loss will occur.
