### ISSUE TITLE
Cursor position is not set correctly after restore 

### ISSUE THREAD

**Issue by Debashish-Mallick** [streamnative/pulsar-flink#362]
Connector version used : pulsar-flink-connector_2.11-**2.4.28.6**.jar
Initial 3 messages are getting lost after restore. We are using 3 partitioned topic.
Getting below exception. Additional log information already provided over the mail. 

2021-06-18 11:27:54.383 [Async calls on Source: src13 -> (src13_monitoring, invalid_data_topic_monitoring, Sink: invalid_data_topic, String_to_JsonNode -> Timestamps/Watermarks) (3/8)] WARN  o.a.flink.streaming.connectors.pulsar.internal.PulsarFetcher  - **Failed to commit cursor to Pulsar.**
java.lang.RuntimeException: **Failed to commit cursor offset 239:31:1:0 for persistent://public/default/src13-partition-1**
                    at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.commitCursorToOffset(PulsarMetadataReader.java:265)
                    at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.doCommitOffsetToPulsar(PulsarFetcher.java:459)
                    at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.commitOffsetToPulsar(PulsarFetcher.java:447)
                    at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.notifyCheckpointComplete(FlinkPulsarSource.java:742)
                    at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.notifyCheckpointComplete(AbstractUdfStreamOperator.java:130)
                    at org.apache.flink.streaming.runtime.tasks.StreamTask.notifyCheckpointComplete(StreamTask.java:842)
                    at org.apache.flink.runtime.taskmanager.Task$2.run(Task.java:1214)
                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.pulsar.client.admin.PulsarAdminException: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_147,147,1442040702) has been shut down
                    at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:228)
                    at org.apache.pulsar.client.admin.internal.TopicsImpl.resetCursor(TopicsImpl.java:864)
                    at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.commitCursorToOffset(PulsarMetadataReader.java:255)
                    ... 11 common frames omitted
Caused by: org.apache.pulsar.shade.org.glassfish.hk2.api.MultiException: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_147,147,1442040702) has been shut down
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:106)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.FactoryCreator.dispose(FactoryCreator.java:173)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:542)
                    at org.apache.pulsar.shade.org.glassfish.jersey.inject.hk2.RequestContext.lambda$findOrCreate$0(RequestContext.java:84)
                    at org.apache.pulsar.shade.org.glassfish.jersey.internal.inject.ForeignDescriptorImpl.dispose(ForeignDescriptorImpl.java:87)
                    at org.apache.pulsar.shade.org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance.remove(Hk2RequestScope.java:150)
                    at java.lang.Iterable.forEach(Iterable.java:75)
                    at org.apache.pulsar.shade.org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance.release(Hk2RequestScope.java:167)
                    at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.release(RequestScope.java:270)
                    at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:416)
                    at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
                    at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
                    at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
                    at org.apache.pulsar.client.admin.internal.TopicsImpl.resetCursor(TopicsImpl.java:861)
                    ... 12 common frames omitted
Caused by: java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_147,147,1442040702) has been shut down
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2393)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandleImpl(ServiceLocatorImpl.java:635)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:628)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:646)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:103)
                    ... 25 common frames omitted
2021-06-18 11:27:54.383 [Async calls on Source: src13 -> (src13_monitoring, invalid_data_topic_monitoring, Sink: invalid_data_topic, String_to_JsonNode -> Timestamps/Watermarks) (2/8)] WARN  o.a.flink.streaming.connectors.pulsar.internal.PulsarFetcher  - **Failed to commit cursor to Pulsar.**
java.lang.RuntimeException: **Failed to commit cursor offset 242:12:2:0 for persistent://public/default/src13-partition-2**
                    at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.commitCursorToOffset(PulsarMetadataReader.java:265)
                    at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.doCommitOffsetToPulsar(PulsarFetcher.java:459)
                    at org.apache.flink.streaming.connectors.pulsar.internal.PulsarFetcher.commitOffsetToPulsar(PulsarFetcher.java:447)
                    at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.notifyCheckpointComplete(FlinkPulsarSource.java:742)
                    at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.notifyCheckpointComplete(AbstractUdfStreamOperator.java:130)
                    at org.apache.flink.streaming.runtime.tasks.StreamTask.notifyCheckpointComplete(StreamTask.java:842)
                    at org.apache.flink.runtime.taskmanager.Task$2.run(Task.java:1214)
                    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
                    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                    at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.pulsar.client.admin.PulsarAdminException: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_152,152,1739628094) has been shut down
                    at org.apache.pulsar.client.admin.internal.BaseResource.getApiException(BaseResource.java:228)
                    at org.apache.pulsar.client.admin.internal.TopicsImpl.resetCursor(TopicsImpl.java:864)
                    at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.commitCursorToOffset(PulsarMetadataReader.java:255)
                    ... 11 common frames omitted
Caused by: org.apache.pulsar.shade.org.glassfish.hk2.api.MultiException: A MultiException has 1 exceptions.  They are:
1. java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_152,152,1739628094) has been shut down
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:106)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.FactoryCreator.dispose(FactoryCreator.java:173)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:542)
                    at org.apache.pulsar.shade.org.glassfish.jersey.inject.hk2.RequestContext.lambda$findOrCreate$0(RequestContext.java:84)
                    at org.apache.pulsar.shade.org.glassfish.jersey.internal.inject.ForeignDescriptorImpl.dispose(ForeignDescriptorImpl.java:87)
                    at org.apache.pulsar.shade.org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance.remove(Hk2RequestScope.java:150)
                    at java.lang.Iterable.forEach(Iterable.java:75)
                    at org.apache.pulsar.shade.org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance.release(Hk2RequestScope.java:167)
                    at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.release(RequestScope.java:270)
                    at org.apache.pulsar.shade.org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:416)
                    at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:765)
                    at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:456)
                    at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:357)
                    at org.apache.pulsar.client.admin.internal.TopicsImpl.resetCursor(TopicsImpl.java:861)
                    ... 12 common frames omitted
Caused by: java.lang.IllegalStateException: ServiceLocatorImpl(__HK2_Generated_152,152,1739628094) has been shut down
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.checkState(ServiceLocatorImpl.java:2393)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandleImpl(ServiceLocatorImpl.java:635)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:628)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.ServiceLocatorImpl.getServiceHandle(ServiceLocatorImpl.java:646)
                    at org.apache.pulsar.shade.org.jvnet.hk2.internal.FactoryCreator.getFactoryHandle(FactoryCreator.java:103)
                    ... 25 common frames omitted

**Comment by jianyun8023** [comment]
This question is the same as #357.

**Comment by syhily** [comment]
Closed for it has been resolved.
