### ISSUE TITLE
[BUG] flink sql client Failed to access pulsar

### ISSUE THREAD

**Issue by riritack** [streamnative/pulsar-flink#372]
ddl ：
  CREATE TABLE pulsar_test(
  uuid string,
  name string,
  description string,
  weight string,
  ts string
) WITH (
  'connector' = 'pulsar',
  'topic' = 'persistent://test/ods/ods_test/',
  'format' = 'ogg-json',
  'service-url' = 'pulsar://pulsar-cluster1.scc.com:6650',
  'admin-url' = 'http://pulsar-cluster1.scc.com:8080',
  'scan.startup.mode' = 'earliest' ,
  'sink.semantic' = 'exactly-once'
)；
select * from pulsar_test；
error reason：
java.io.IOException: Cannot connect to the client to send back the stream
	at org.apache.flink.streaming.experimental.CollectSink.open(CollectSink.java:86)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:46)
	at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:428)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$2(StreamTask.java:543)
	at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:93)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:533)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:573)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:755)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:570)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:244)
	at org.apache.flink.streaming.experimental.CollectSink.open(CollectSink.java:82)
	... 11 more

**Comment by jianyun8023** [comment]
@riritack This problem should have nothing to do with the pulsar flink connector.  Please confirm that flink cluster is available.
