### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.client.admin.PulsarAdmin

### ISSUE THREAD

**Issue by ericshao** [streamnative/pulsar-flink#390]
**Describe the bug**
When using pulsar-flink-connector 1.12.2.0, flink 1.12.2 on native k8s, pulsar 2.7.2
the NoClassDefFoundError is occurred:

`
java.lang.NoClassDefFoundError: Could not initialize class org.apache.pulsar.client.admin.PulsarAdmin
  at org.apache.flink.streaming.connectors.pulsar.internal.PulsarClientUtils.newAdminFromConf(PulsarClientUtils.java:34) ~[blob_p-0f0317e691cc8514e6267211d5603c6aa128de24-5473943c445c9b47122d430551b08b07:?]
  at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.<init>(PulsarMetadataReader.java:91) ~[blob_p-0f0317e691cc8514e6267211d5603c6aa128de24-5473943c445c9b47122d430551b08b07:?]
  at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.createMetadataReader(FlinkPulsarSource.java:514) ~[blob_p-0f0317e691cc8514e6267211d5603c6aa128de24-5473943c445c9b47122d430551b08b07:?]
  at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.open(FlinkPulsarSource.java:450) ~[blob_p-0f0317e691cc8514e6267211d5603c6aa128de24-5473943c445c9b47122d430551b08b07:?]
  at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:34) ~[flink-dist_2.11-1.12.2.jar:1.12.2]
  at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102) ~[flink-dist_2.11-1.12.2.jar:1.12.2]
  at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:428) ~[flink-dist_2.11-1.12.2.jar:1.12.2]
  at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$2(StreamTask.java:543) ~[flink-dist_2.11-1.12.2.jar:1.12.2]
  at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:93) ~[flink-dist_2.11-1.12.2.jar:1.12.2]
`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by azui007** [comment]
Hello, I have the same problem. Can you tell me how you solved it. thank you

**Comment by pisceslj** [comment]
package the  org.slf4j:jul-to-slf4j into your jar
