### ISSUE TITLE
[FEATURE] allow set 'pulsar.producer.blockIfQueueFull' = 'true' in sql

### ISSUE THREAD

**Issue by nlu90** [streamnative/pulsar-flink#413]
**Is your feature request related to a problem? Please describe.**

Some query caused the following error:
```
2021-09-01 11:34:12
org.apache.flink.runtime.JobException: Recovery is suppressed by NoRestartBackoffTimeStrategy
   ...
Caused by: org.apache.flink.streaming.runtime.tasks.AsynchronousException: Caught exception while processing timer.
   ...
Caused by: TimerException{org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator}
    ... 11 more
Caused by: org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator
    ...
Caused by: org.apache.flink.streaming.runtime.tasks.ExceptionInChainedOperatorException: Could not forward element to next operator
    ...
Caused by: java.lang.Exception: Failed to send data to Pulsar: Producer send queue is full
    at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSinkBase.checkErroneous(FlinkPulsarSinkBase.java:563)
    at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSink.invoke(FlinkPulsarSink.java:96)
    at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSink.invoke(FlinkPulsarSink.java:41)
    at org.apache.flink.streaming.api.functions.sink.TwoPhaseCommitSinkFunction.invoke(TwoPhaseCommitSinkFunction.java:223)
    at org.apache.flink.table.runtime.operators.sink.SinkOperator.processElement(SinkOperator.java:72)
    at org.apache.flink.streaming.runtime.tasks.CopyingChainingOutput.pushToOperator(CopyingChainingOutput.java:71)
    ... 26 more
Caused by: org.apache.pulsar.client.api.PulsarClientException$ProducerQueueIsFullError: Producer send queue is full
    at org.apache.pulsar.client.impl.ProducerImpl.canEnqueueRequest(ProducerImpl.java:763)
    at org.apache.pulsar.client.impl.ProducerImpl.sendAsync(ProducerImpl.java:393)
    at org.apache.pulsar.client.impl.ProducerImpl.internalSendAsync(ProducerImpl.java:292)
    at org.apache.pulsar.client.impl.ProducerImpl.internalSendWithTxnAsync(ProducerImpl.java:363)
    at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendWithTxnAsync(PartitionedProducerImpl.java:191)
    at org.apache.pulsar.client.impl.PartitionedProducerImpl.internalSendAsync(PartitionedProducerImpl.java:167)
    at org.apache.pulsar.client.impl.TypedMessageBuilderImpl.sendAsync(TypedMessageBuilderImpl.java:103)
    at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSink.invoke(FlinkPulsarSink.java:112)
    ... 30 more
```

**Describe the solution you'd like**
want to allow set 'pulsar.producer.blockIfQueueFull' = 'true' for the query or on the table

.

**Comment by haormj** [comment]
@nlu90 you can use it like  'properties.pulsar.producer.block-if-queue-full' = 'true'

**Comment by nlu90** [comment]
@haormj thanks for the reply.

Why it's `block-if-queue-full` separated by hyphen instead of the README doc said `pulsar.producer.blockIfQueueFull`?

**Comment by syhily** [comment]
Duplicated by #419. Close this issue for tracking everything in the new issue. PING me if you think we should keep this issue open. @nlu90
