### ISSUE TITLE
[BUG] After version update from 2.7.5.3 to 2.7.6 job can't restore from its checkpoint

### ISSUE THREAD

**Issue by mrbazzik** [streamnative/pulsar-flink#460]
**Describe the bug**
We have a Flink job which reads data from a Pulsar topic.
It has the following dependency in `build.sbt`:
`"io.streamnative.connectors" % "pulsar-flink-connector-2.12-1.12" % "2.7.5.3"`
After we updated the connector to be of `2.7.6` version, we tried to start the job from the latest checkpoint/savepoint. The job fails at the start, because it can't deserialize its source state:
```log
org.apache.flink.util.StateMigrationException: The new state typeSerializer for operator state must not be incompatible.
 at org.apache.flink.runtime.state.DefaultOperatorStateBackend.getListState(DefaultOperatorStateBackend.java:300)
 at org.apache.flink.runtime.state.DefaultOperatorStateBackend.getUnionListState(DefaultOperatorStateBackend.java:216)
 at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.tryMigrateState(FlinkPulsarSource.java:789)
 at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.initializeState(FlinkPulsarSource.java:736)
 at org.apache.flink.streaming.util.functions.StreamingFunctionUtils.tryRestoreFunction(StreamingFunctionUtils.java:189)
 at org.apache.flink.streaming.util.functions.StreamingFunctionUtils.restoreFunctionState(StreamingFunctionUtils.java:171)
 at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.initializeState(AbstractUdfStreamOperator.java:96)
 at org.apache.flink.streaming.api.operators.StreamOperatorStateHandler.initializeOperatorState(StreamOperatorStateHandler.java:111)
 at org.apache.flink.streaming.api.operators.AbstractStreamOperator.initializeState(AbstractStreamOperator.java:290)
 at org.apache.flink.streaming.runtime.tasks.OperatorChain.initializeStateAndOpenOperators(OperatorChain.java:427)
 at org.apache.flink.streaming.runtime.tasks.StreamTask.lambda$beforeInvoke$2(StreamTask.java:543)
 at org.apache.flink.streaming.runtime.tasks.StreamTaskActionExecutor$SynchronizedStreamTaskActionExecutor.runThrowing(StreamTaskActionExecutor.java:93)
 at org.apache.flink.streaming.runtime.tasks.StreamTask.beforeInvoke(StreamTask.java:533)
 at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:573)
 at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:755)
 at org.apache.flink.runtime.taskmanager.Task.run(Task.java:570)
 at java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**
1. Have this in `build.sbt` of your Flink job's project: `"io.streamnative.connectors" % "pulsar-flink-connector-2.12-1.12" % "2.7.5.3"`
2. Run the job and make sure it created a checkpoint or do a manual savepoint.
3. Change the line in `build.sbt` to: `"io.streamnative.connectors" % "pulsar-flink-connector-2.12-1.12" % "2.7.6"`
4. Start the updated job from the checkpoint/savepoint.
5. See the error.

**Expected behavior**
Not sure if it's expected, but I think it should have backward compatibility with the previously serialized source state.

**Comment by syhily** [comment]
I think this is a known bug. Which is caused by the incompatible pulsar-client. This old release is not maintained anymore. Can you just use the newly [released connector](https://mvnrepository.com/artifact/io.streamnative.connectors/pulsar-flink-connector)?

BTW, we don't have the state migration tool for the old state in `2.7.5.3`. But we promise the state in this new connector would be automatically migrated.

**Comment by mrbazzik** [comment]
Thanks for the answer. Yeah, we'll switch to the new connector. We just hoped the transition would be smooth, allowing us to preserve exactly-once guarantee. But I guess we'll have to start with a clean source state, meaning there will be some data loss or duplicates. I suppose we can do nothing about it, hopefully we'll not have this problem with the new connector.

**Comment by Raven888888** [comment]
Faced same issue in https://github.com/streamnative/pulsar-flink/issues/256#issuecomment-954422346. Thanks for telling that old connector is no longer maintained.

**Comment by syhily** [comment]
Closed.
