### ISSUE TITLE
[BUG]Getting java.lang.IllegalStateException: InjectionManagerFactory not found

### ISSUE THREAD

**Issue by mrbazzik** [streamnative/pulsar-flink#68]
**Describe the bug**
Running a simple Flink job on AWS EMR to read from a Pulsar topic produces an error: 
```
Caused by: org.apache.flink.runtime.client.JobExecutionException: Job execution failed.
	at org.apache.flink.runtime.jobmaster.JobResult.toJobExecutionResult(JobResult.java:146)
	at org.apache.flink.client.program.rest.RestClusterClient.submitJob(RestClusterClient.java:259)
	... 23 more
Caused by: java.lang.IllegalStateException: InjectionManagerFactory not found.
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.inject.Injections.lambda$lookupInjectionManagerFactory$0(Injections.java:98)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.inject.Injections.lookupInjectionManagerFactory(Injections.java:98)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.inject.Injections.createInjectionManager(Injections.java:68)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:432)
	at org.apache.pulsar.shade.org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:341)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:826)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:285)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:143)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:112)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:108)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:99)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$AsyncInvoker.method(JerseyInvocation.java:706)
	at org.apache.pulsar.shade.org.glassfish.jersey.client.JerseyInvocation$AsyncInvoker.get(JerseyInvocation.java:566)
	at org.apache.pulsar.client.admin.internal.BaseResource.asyncGetRequest(BaseResource.java:165)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.getPartitionedTopicMetadataAsync(TopicsImpl.java:283)
	at org.apache.pulsar.client.admin.internal.TopicsImpl.getPartitionedTopicMetadata(TopicsImpl.java:267)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.getTopicPartitionsAll(PulsarMetadataReader.java:347)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.getTopicPartitions(PulsarMetadataReader.java:337)
	at org.apache.flink.streaming.connectors.pulsar.internal.PulsarMetadataReader.discoverTopicChanges(PulsarMetadataReader.java:118)
	at org.apache.flink.streaming.connectors.pulsar.FlinkPulsarSource.open(FlinkPulsarSource.java:350)
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36)
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:532)
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:396)
	at org.apache.flink.runtime.taskmanager.Task.doRun(Task.java:705)
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:530)
	at java.lang.Thread.run(Thread.java:748)`
```

**To Reproduce**
1. AWS EMR cluster 5.29.0 (Hadoop 2.8.5, Flink 1.9.1, Scala 2.11)
2. Dependencies in build.sbt:
```
`ThisBuild / scalaVersion := "2.11.12"`
`val flinkVersion = "1.9.1"`
`val pulsarVersion = "2.4.9"`
`val flinkDependencies = Seq(`
`  "org.scalactic" %% "scalactic" % "3.1.1",`
`  "org.scalatest" %% "scalatest" % "3.1.1" % "test",`
`  "org.apache.flink" %% "flink-scala" % flinkVersion, `
`  "org.apache.flink" %% "flink-streaming-scala" % flinkVersion, `
`  "io.streamnative.connectors" %% "pulsar-flink-connector" % pulsarVersion,`
`)`
```
3. Read from a Pulsar topic with:
```
`val env = StreamExecutionEnvironment.getExecutionEnvironment`
`env.addSource(
        new FlinkPulsarRowSource(admin_url, conf, props).setStartFromEarliest()
).print()`
```

**Comment by jiazhai** [comment]
@mrbazzik This looks like a shade issue.  Would you please help try on latest version? 
@yjshen have already solved some shade issues.

**Comment by mrbazzik** [comment]
I've tried with pulsar-flink-connector 2.4.11 with the same result.
I tried to google this, the only thing I found was: https://github.com/apache/pulsar/pull/1274#issuecomment-368071945, which, I guess, was about some differences in jersey 2.25 vs 2.26. But from my understanding jersey 2.27 is shaded inside pulsar-client-admin, so not sure what's going on.

**Comment by mrbazzik** [comment]
I think I found the cause, it was my fault. I misconfigured sbt `assembly` plugin so that it removed `services` section from the resulting jar during merging process. As a result no service provider could be found for `InjectionManagerFactory`. Closing the issue, sorry for bothering

**Comment by hangc0276** [comment]
> I think I found the cause, it was my fault. I misconfigured sbt `assembly` plugin so that it removed `services` section from the resulting jar during merging process. As a result no service provider could be found for `InjectionManagerFactory`. Closing the issue, sorry for bothering

@mrbazzik hi, would you please share your sbt configuration of this problem? I also faced this problem, how did you solved it. thanks.

**Comment by TalkWIthKeyboard** [comment]
> > I think I found the cause, it was my fault. I misconfigured sbt `assembly` plugin so that it removed `services` section from the resulting jar during merging process. As a result no service provider could be found for `InjectionManagerFactory`. Closing the issue, sorry for bothering
> 
> @mrbazzik hi, would you please share your sbt configuration of this problem? I also faced this problem, how did you solved it. thanks.

@hangc0276 hi, have you solved this problem? I also faced this problem too.
